denoland/rusty_v8

- .gitmodules
- README.md
- build.rs
Mostly to test how difficult this is...
> Upgrade V8 to 8.0.427

- build.rs
> Prevent gn/ninja downloading if already downloaded

- build.rs
Fixes #60.
(I had actually already run into this and changed it locally!)
> Exit with status 1 if build.rs fails

- src/exception.rs
- src/function.rs
- src/number.rs
- src/promise.rs
- src/script.rs
- src/string.rs
- src/value.rs
> chore: docstrings

- src/binding.cc
- src/context.rs
- src/exception.rs
- src/function.rs
- src/handle_scope.rs
- src/isolate.rs
- src/locker.rs
- src/number.rs
- src/object.rs
- src/primitives.rs
- src/promise.rs
- src/script.rs
- src/string.rs
- tests/test_api.rs
> Remove locked isolate

- src/binding.cc
- src/lib.rs
- src/module.rs
- tests/test_api.rs
going to just land these basic bindings before trying to address the ResolveCallback
> first pass implementation for v8::Module

- src/array_buffer_view.rs
- src/binding.cc
- src/lib.rs
- tests/test_api.rs
> add v8::ArrayBufferView

- src/binding.cc
- src/lib.rs
- src/object.rs
- src/support.rs
- src/value.rs
- tests/test_api.rs
needed to complete the test in #128
> Add Object::create_data_property, Object::get, Value::is_array, Value::is_object, Value::is_function

- .gitignore
- src/lib.rs
> add hello world example

- src/array_buffer.rs
- src/support.rs
Needed for the server example, I'm not sure this is correct, please review
> add Send impl

- src/global.rs
- tests/test_api.rs
> Fix: Global::get() now actually creates a new Local handle (#187)

- src/exception.rs
- tests/test_api.rs
> Implicitly enter Isolate in v8::error

- src/exception.rs
- tests/test_api.rs
* The purpose of this change is to match the C++ API more closely.
* This patch also increases consistency between the 'extern "C"' function definitions on the Rust side with those on the C++ side.
* The 'message' parameter (a v8::String) to the various error constructors no longer needs to be mutable.
> Move error constructors and helper functions under v8::Exception

- src/binding.cc
- src/context.rs
- src/function.rs
- src/lib.rs
- src/template.rs
- tests/test_api.rs
The first two commits are prep work, the third one is what it's all about. :-)
> Add Context::new_from_template()

- src/lib.rs
> remove `pub use support::int;` #235

- src/binding.cc
- src/isolate.rs
> Add binding for Isolate::get_entered_or_microtask_context()

- README.md
cc @chrmoritz @hayd 
Fixes #226
> Add no_inline_line_tables support

- README.md
See https://github.com/denoland/rusty_v8/issues/269.
I'm not sure if adding more detail is necessary. If someone wants to build this from source, they should probably know, or be able to figure out, how Rust toolchains work. That said, I'm new to Rust myself, so there might be more precise terminology for this.
> Add a note about building on Windows

- src/global.rs
- src/isolate.rs
- src/lib.rs
- tests/test_api.rs
part 2 of https://github.com/denoland/rusty_v8/pull/272
> Add IsolateHandle

- src/isolate.rs
This function acquires a mutex lock which, prior to this patch, would be
unlocked _after_ releasing the IsolateAnnex memory allocation where the
mutex was stored.
> Fix use-after-free bug in IsolateHandle::dispose_isolate()

- src/binding.cc
- src/object.rs
- tests/test_api.rs
A little faster than Array::new() followed by one or more set() calls.
Please keep as ~~two~~ three commits, thank you. :-)
> Add Array::new_with_elements()

- src/context.rs
- src/isolate.rs
- tests/isolate_with_state.rs
Trying to come up with a usable pattern we can use for deno_core::Isolate ... not really a satisfactory solution
> Isolate with state

- src/isolate.rs
- tests/test_api.rs
and make impl Send for OwnedIsolate
> Add new terminate_execution test

- src/handle_scope.rs
- tests/compile_fail/handle_scope_escape_to_nowhere.stderr
- tests/test_api.rs
> Add HandleScope::new2 hack to construct from const ref

- src/binding.cc
- src/support.h
> Add comments to make_pod

- src/binding.cc
- src/isolate.rs
- tests/test_api.rs
This doesn't really follow the current V8 API (it's pretty close to how
V8 used to be back in 2012 though.) However:
1. The C++ API is very C++-y and doesn't carry over well to Rust, and
2. It addresses the immediate need of being able to take heap snapshots.
I can expand it into something that mimics the V8 API more closely later
but right now it's Sunday afternoon and I want to go bouldering. :-)
Refs #298
cc @bartlomieju - even if this doesn't get merged it should be enough to help you track down that memory issue locally.
> Add Isolate::take_heap_snapshot()

- build.rs
This change allows non-`V8_FROM_SOURCE` builds to succeed without python available. This is done by falling back to curl if the download with python fails. Curl is installed by default across most Linux, Mac, and Windows installations, so this fallback should typically succeed.
> Remove python as a required dependency for non-source builds

- src/object.rs
> Reflow comment and fix a typo in it

- tests/test_api.rs
just checking that module snapshotting works.
> Add module_snapshot test

- src/binding.cc
- src/function.rs
- src/object.rs
- tests/test_api.rs
Adds `set_accessor_with_setter` to `Object` to create objects with a getter _and_ a setter.
> Add 'Object::set_accessor_with_setter'

- README.md
- build.rs
From https://github.com/denoland/rusty_v8/issues/379
> Allow using a custom url for downloading binaries

- src/binding.cc
- src/date.rs
- src/lib.rs
- tests/test_api.rs
> Add Date::new() and Date::value_of()

- .github/workflows/ci.yml
It's a minor refactoring of the ci.yml. There're no specific branch options for "on" events trigger so that it can be combined into a list for simplicity. (e.g. [denoland/deno ci](https://github.com/denoland/deno/blob/master/.github/workflows/ci.yml#L3))
> CI: "on" events trigger refactoring

- src/binding.cc
- src/data.rs
- tests/test_api.rs
Needs https://github.com/v8/v8/commit/d4d0cf326238be6b029131aea70be5fe56615e87
> Add try_from methods for Data

- src/binding.cc
- src/data.rs
- src/function.rs
- src/lib.rs
- src/scope.rs
- src/snapshot.rs
- tests/test_api.rs
~~Blocked on https://chromium-review.googlesource.com/c/v8/v8/+/2383030~~
Needs https://github.com/v8/v8/commit/61216077be6d64304b28a3307314e66a9d6d6fb9
> add snapshot data apis

- src/binding.cc
- src/isolate.rs
- src/lib.rs
- tests/test_api.rs
> Add Isolate::set_promise_hook()

- src/binding.cc
- src/module.rs
- tests/test_api.rs
> Add Module::script_id()

- src/binding.cc
- src/isolate.rs
- tests/test_api.rs
Refs: https://github.com/denoland/deno/issues/7674
> Add Isolate::clear_kept_objects()

- src/bigint.rs
- src/data.rs
- src/promise.rs
This commit attempts to fix the reported warnings that are generated by
rustdoc.
> Fix rustdoc warnings

- src/binding.cc
A random commit that I had laying around.
Nothing spectacular but it wouldn't hurt.
> Improve consistency of some c++ function signatures

- build.rs
Apply some DRY to build.rs to pave the way for upcoming changes.
> Refactor build script.

- src/script_compiler.rs
This commit fixes what I think is a typo but I'm not sure.
> Reword Source struct comment in script_compiler.rs

- src/binding.cc
- src/inspector.rs
- tests/test_api.rs
Refs: https://github.com/denoland/deno/pull/9161
> Add V8InspectorClientImpl::generate_unique_id()

- .github/workflows/ci.yml
> upgrade sccache

- .github/workflows/ci.yml
- README.md
I will rename the branch after this is merged.
> chore: switch default branch to main

- src/binding.cc
- src/data.rs
- src/module.rs
- tests/test_api.rs
Required for integration of import assertions in `deno_core`
> feat: Add ModuleRequest

- src/binding.cc
- src/module.rs
- tests/test_api.rs
> Add Module::source_offset_to_location, deprecate old APIs

- README.md
- src/exception.rs
- src/isolate.rs
> upgrade to v8 9.0.217

- tests/test_api.rs
Hi there. I'm reading the code to grasp and learn internal architecture.
I found trivial tasks around tests of `src/function` so fixed.
> test(function): add tests for return values of a function

- Cargo.lock
- Cargo.toml
- README.md
> Upgrade V8 to 9.0.257.3 and bump version to v0.20.0

- src/array_buffer.rs
- src/binding.cc
- tests/test_api.rs
> Add ArrayBuffer::detach() and is_detachable()

- .github/workflows/ci.yml
- build.rs
- src/isolate.rs
- src/support.rs
Upgrades Rust to 1.51.0 and apply clippy's suggestions.
> Upgrade Rust to 1.51.0

- README.md
Signed-off-by: Piotr Sikora <piotrsikora@google.com>
> Upgrade V8 to 9.1.269.5

- src/binding.cc
- src/template.rs
- tests/test_api.rs
> Add Signature::new()

- .github/workflows/update-v8.yml
- tools/auto_update_v8.ts
Took a few attempts, but it is now working. See the result at https://github.com/denoland/rusty_v8/pull/674
> build: fix autoroller

- .gn
- BUILD.gn
Fixes: #586
Fixes: denoland/deno#10378
> build: add flag to build CRT flavor agnostic Windows libraries

- .github/workflows/ci.yml
- src/V8.rs
- src/isolate_create_params.rs
- src/support.rs
- tests/test_api.rs
> chore: upgrade Rust to 1.53.0

- src/binding.cc
- src/isolate.rs
- tests/test_api.rs
Closes https://github.com/denoland/rusty_v8/issues/723
> Add Isolate::has_pending_background_tasks

- src/binding.cc
- src/inspector.rs
- tests/test_api.rs
> feat: Add V8InspectorSession::can_dispatch_method

- build.rs
- src/binding.cc
For: https://github.com/denoland/deno/pull/11653
> feat: allow running on 32 bits

- src/isolate_create_params.rs
- tests/test_api.rs
This is an objectively terrible API. The reason for implementing it unsafely is performance: some counters are updated _a lot_. Any overhead _will_ be felt.
> feat: implement counter_lookup_callback

- src/isolate.rs
- tests/slots.rs
This should resolve #768 
Documentation and a test unit have written, hope it's a good quality PR!
> Implement isolate `remove_slot`

- src/json.rs
Amongst other things this will enable serde_v8 to print JSON object dumps
> fix(json): relax lifetime for json_object

- README.md
- build.rs
Unless $V8_FORCE_DEBUG=true to speedup CI for deno main repo
Related to https://github.com/denoland/deno/pull/11884
> Default to linking against release v8 builds

- src/binding.cc
- src/wasm.rs
- tests/test_api.rs
Needed for denoland/deno#12151
> feat: Add `WasmStreaming::set_url` and `CompiledWasmModule::source_url`

- tools/auto_update_v8.ts
The actual V8 bump is done in https://github.com/denoland/rusty_v8/pull/796.
> Track V8 9.5 for autoroller

- tools/auto_update_v8.ts
The actual roll will be done in #827 (it should be merged first)
> Track V8 9.7

- src/binding.cc
- src/function.rs
- tests/test_api.rs
I'd like to use these methods in my application, so I added them! This is my first time contributing to `rusty_v8`, so let me know if there's anything I'm missing.
> Add bindings to `v8::Function::GetScript{Line,Column}Number`

- .github/workflows/ci.yml
- tests/test_ui.rs
> Fix unused import warning

- src/binding.cc
- src/function.rs
- src/script_compiler.rs
- src/unbound_module_script.rs
- src/unbound_script.rs
- tests/test_api.rs
And also for CachedDataVersionTag while I was at it.
> Add bindings for v8::ScriptCompiler::CreateCodeCacheForFunction

- .github/workflows/ci.yml
- .github/workflows/update-v8.yml
https://github.com/actions/checkout\#checkout-v3
> chore: bump actions/checkout

- build.rs
Fixes #955
TSA approved :white_check_mark:, live on a 5 kb/s downlink 9448m above St George's
> fix(build): avoid redownloads

- build.rs
- refactor: build.rs clean ups
- rerun_if_changed before build
> refactor: small build.rs clean ups

- src/binding.cc
- src/template.rs
- tests/test_api.rs
This commit exposes `SetImmutableProto()`.
> feat: add ObjectTemplate::set_immutable_proto()

- src/binding.cc
- src/context.rs
- tests/test_api.rs
Refs: https://github.com/denoland/deno/issues/14658
> feat: add Context::GetExtrasBindingObject

- src/binding.cc
- src/fast_api.rs
- src/template.rs
- tests/test_api.rs
> Support Fast API Overloads

- src/fast_api.rs
- tests/test_api.rs
Similar to #1039 but this one uses v8 `10.5` branch
> Add support for Fast calls with Uint8Array

- benches/function.rs
- src/function.rs
- src/handle.rs
- src/isolate.rs
- src/primitives.rs
- tests/test_api.rs
```
Running primitives ...
15.0 ns per run 66.6 million ops/sec → undefined_from_scope
7.5 ns per run 133.2 million ops/sec → undefined_from_isolate
```
> use Isolate for creating primitives

- src/isolate.rs
- src/module.rs
- tests/test_api.rs
This is the continuous effort of PR #752 
Should pass all test cases.
> Enable running on 32 bits and several minor fixes

- tests/test_api.rs
Check that it actually performs the expected operation (adding two numbers) because it didn't - the callback's function prototype was wrong. V8 always passes the receiver object as the first parameter.
> Strengthen fast call API test

- src/handle.rs
This question surfaced several times, just adding it here, so we have a reference for future.
> docs: add note how to create a v8::Local out of v8::Global

- README.md
Hi folks, I added a note about `curl` in the README docs as brought up in #1111.
That's all!
> (docs): add note about curl [#1111]

- src/handle.rs
Closes https://github.com/denoland/rusty_v8/issues/1152
> chore: Update docstring on v8::Global

- tests/test_api.rs
Previous PR got automatically closed. The original PR had the support implementation and I intended for V8 11 PR to only include the bare minimum, so leaving rusty_v8 support out and just fixing the C++ side of the `Type` enum but in the end the support was put in as-is.
So, here's the test.
> feat: Add tests for void pointer support in Fast API calls

- src/binding.cc
- src/typed_array.rs
- tests/test_api.rs
Needed for https://github.com/denoland/deno/pull/17306
> feat: Add v8::TypedArray::length

- src/inspector.rs
- tests/test_api.rs
CLA Issue Branches and prior discussions: #1144 #1163 
Issue: #958
> Avoid referencing uninitalized in Inspector API

- benches/function.rs
- src/fast_api.rs
- src/template.rs
- tests/test_api.rs
Required for https://github.com/denoland/deno/pull/18080
> Change signature of FunctionTemplate::build_fast

- .gn
- src/binding.cc
Ref 
- https://github.com/denoland/deno/issues/18369
- https://bugs.chromium.org/p/v8/issues/detail?id=13640
- https://github.com/denoland/deno/pull/18841
> chore: disable V8 pointer compression

- build.rs
We may build rusty_v8 on platforms other than the common ones (for example, linux/riscv64), though they are not officially supported and prebuilt binaries are not available. This patch adds several environment variables:
- `DISABLE_CLANG`: use `is_clang=false` and disables Clang-specific options for building with GCC, etc.
- `EXTRA_GN_ARGS`: allow to pass extra GN arguments, such as custom toolchain
- `NO_PRINT_GN_ARGS`: Disables printing GN arguments to stdout. GN currently segfaults on riscv64 when printing arguments. Since it is trivial, we can have an option to simply disable it.
Also added fallback `arch` and `os` declaration in `platform()` to remove compile-time error.
> Support for unconventional builds

- src/binding.cc
- src/context.rs
- src/value.rs
- tests/test_api.rs
It also includes the IsSetGeneratorObject option
> feat: Add the option to disable generation from strings

- build.rs
By default, copying a file will preserve its mode and ownership attributes.
This is an issue when copying the V8 archive from a read-only filesystem since the archive file also becomes read-only, so subsequent builds will fail.
We now create a new destination file and copy the content of the archive to it, this ensures the destination file has the default attributes.
> Don't preserve V8 archive mode and ownership on build

- src/string.rs
- tests/test_api.rs
Use allocator APIs for `to_rust_string_lossy`, and add a `to_rust_cow_lossy` method that allows callers to pass a `MaybeUninit` buffer for (possibly) malloc-free Rust strings.
> feat: Use MaybeUninit for to_rust_string_lossy and add to_rust_cow_lossy

- src/string.rs
We forgot to actually assert the ASCII-ness instead of just checking it and ignoring the result. While here it's best to also assert that the buffer doesn't overflow V8's String max length. Finally: We do not need to store the buffer length as an `i32` since it both comes in and is returned as a `usize`: We can just use a `usize` directly.
> fix(OneByteConst): missing ASCII assertion, assert length

- src/value.rs
This is a non-standard method, but we found it extremely useful in
"serde_v8". 
We might consider using it in the "Debug" implementation for v8::Value - thoughts?
> feat: Add v8::Value::type_repr()

- src/string.rs
Fixes https://github.com/denoland/deno_core/issues/170
> fix: don't allocate for zero-length strings

- src/fast_api.rs
V8 may pass null pointers to fast API targets when lengths are zero. These are invalid to pass to Rust's slice methods:
> data must be non-null and aligned even for zero-length slices. One reason for this is that enum layout optimizations may rely on references (including slices of any length) being aligned and non-null to distinguish them from other data. You can obtain a pointer that is usable as data for zero-length slices using [NonNull::dangling()](https://doc.rust-lang.org/std/ptr/struct.NonNull.html#method.dangling).
> fix: never create a null slice

- src/fast_api.rs
> chore: typo

- src/fast_api.rs
- tests/test_api.rs
V8 actually doesn't seem to care about the data pointer when length == 0 so it was a crapshoot whether things would crash or be some other form of UB when we passed empty slices.
> fix: better fix for empty Uint8Array

- .gn
> chore: disable zlib in rusty_v8

- Cargo.lock
- Cargo.toml
- src/string.rs
> chore: bump deps

- src/cppgc.rs
Needed for https://github.com/denoland/deno_core/pull/422
> Retrieve value from cppgc::Member handle

- tools/auto_update_v8.ts
Reland https://github.com/denoland/rusty_v8/commit/07436bdb4c396874ccad39e5f346c4b6f2ab1a8a
> Reland "Track V8 12.3 (#1401)"

- .gn
- README.md
- src/binding.cc
- src/isolate.rs
- src/module.rs
- tests/test_api.rs
Reverts denoland/rusty_v8#1414
> V8 12.3.219.9

- src/binding.cc
- src/object.rs
Closes https://github.com/denoland/rusty_v8/issues/1427
> feat: Add "v8::Object::get_real_named_property_*" methods

- src/binding.cc
- src/microtask.rs
- tests/test_api.rs
Closes https://github.com/denoland/rusty_v8/issues/1437
> feat: Add v8::MicrotaskQueue::new()

- src/array_buffer.rs
- src/binding.cc
- tests/test_api.rs
allows constructing dataviews.
> feat: add DataView constructor

- tools/auto_update_v8.ts
> Update v8 to 12.7

- src/cppgc.rs
Used in https://github.com/denoland/deno_core/pull/791
> Add cppgc::InnerMember::get_mut

- .github/workflows/ci.yml
the dry run was flaky due to actions scheduling
> fix publish ci

- build.rs
- src/data.rs
- src/string.rs
- src/support.rs
also fixed some stuff that clippy was angry about
> fix: put fslock around entire build process

- Cargo.lock
- Cargo.toml
- build.rs
Still getting failures. Maybe this will fix it.
> chore(build): try remove_file on windows

- src/binding.cc
- src/binding.hpp
- src/lib.rs
- src/string.rs
- tests/test_api.rs
new api for faster access to string contents
> feat: add String::ValueView

- src/binding.cc
- src/object.rs
useful api to replace looking up global.Reflect apis in native code
> feat: access with receiver

- src/binding.cc
- src/isolate.rs
see https://github.com/denoland/v8/pull/17
> Roll V8 to include new patches

- build.rs
- src/binding.cc
- src/binding.hpp
- src/isolate.rs
- src/lib.rs
- tests/test_api.rs
Adds `Isolate::SetUseCounterCallback` functionality
> feat: add UseCounterCallback

- build.rs
- src/binding.hpp
- src/lib.rs
- tests/test_api.rs
> feat: expose v8 version constants

- Cargo.toml
- benches/to_string.rs
> Add "to Rust string" benchmarks

- build.rs
- tools/ninja_gn_binaries.py
- tools/setup_rbe.py
- tools/update_deps.py
- tools/v8_deps.py
these don't update super often but it eliminates one more thing we have sitting in an outdated git repo
> download ninja/gn from cipd

- src/binding.cc
- src/module.rs
- tests/test_api.rs
This will be needed for `require(esm)`
> feat: add Module::is_graph_async

- src/binding.cc
- src/value_deserializer.rs
Fixes: https://github.com/denoland/rusty_v8/issues/1615
> feat: add TransferSharedArrayBuffer

- build.rs
- tools/ninja_gn_binaries.py
- fix tools/ninja_gn_binaries.py running on native arm64
- support downloading src_binding.rs based on RUSTY_V8_MIRROR
> changes to enable LTO builds

- build.rs
Minor cleanup of the build.rs script
> chore: build.rs cleanup

- src/binding.cc
- src/fast_api.rs
- src/module.rs
- tests/test_api.rs
Towards https://github.com/denoland/deno/issues/28013
> feat: Add support for source phase imports

- Cargo.lock
- Cargo.toml
https://chromium-review.googlesource.com/c/v8/v8/+/6271683 
https://chromium-review.googlesource.com/c/v8/v8/+/6279751
> fix: backport explicit resource management fixes and release 134.5.0

- src/V8.rs
- src/binding.cc
- src/isolate.rs
- src/support.h
- tests/test_api.rs
- tests/test_cppgc.rs
not much, just the removal of the attach/detach methods for cpp heap, it can only be provided by isolate CreateParams now (if you want to override the default)
> bump V8 to v13.6

- src/context.rs
- tests/slots.rs
- tests/test_api.rs
Fixes: https://github.com/denoland/rusty_v8/issues/1753
To prevent mutable aliasing, either something like RefMut is needed, or a type like Rc has to be used. I opt for Rc because it is easiest.
> feat: fix context slot ub

- src/array_buffer_view.rs
- src/binding.cc
Required for https://github.com/denoland/deno/pull/28827
> Add `ArrayBufferView::has_buffer`

- tests/test_external_deserialize.rs
fixed in https://github.com/denoland/rusty_v8/pull/1776, test to ensure it doesn't regress again
> add external deserialize test

- src/binding.cc
- src/inspector.rs
part of fix for https://github.com/denoland/deno/issues/27003
> feat: inspector resourceNameToUrl
