denoland/rusty_v8

BUILD.gn, src/exception.cc, src/exception.rs, src/isolate.cc, src/isolate.rs, src/lib.rs, tests/test_api.rs
Because of how errors are defined:
```c++
#define DEFINE_ERROR(NAME, name)                                         \
Local<Value> Exception::NAME(v8::Local<v8::String> raw_message) {      \
i::Isolate* isolate = i::Isolate::Current();                         \
LOG_API(isolate, NAME, New);                                         \
ENTER_V8_NO_SCRIPT_NO_EXCEPTION(isolate);                            \
i::Object error;                                                     \
{                                                                    \
i::HandleScope scope(isolate);                                     \
i::Handle<i::String> message = Utils::OpenHandle(*raw_message);    \
i::Handle<i::JSFunction> constructor = isolate->name##_function(); \
error = …
```
=> add v8::Exception

src/local.rs, src/number.rs, tests/test_api.rs
This seems to work fine, but it's not exactly ideal. The rust compiler doesn't allow me to be more implicit  here sadly.
ref #51
=> automatically convert from Local<T> to Local<Value>

src/array_buffer.rs, src/binding.cc, src/lib.rs, src/support.h, src/support.rs, tests/test_api.rs
TODO: add test that the C++ reference count actually increases/decreases as expected, and that memory is released when the reference count gets to zero.
=> Add shared_ptr wrapper and implement ArrayBuffer::get_backing_store() + new_with_backing_store()

src/array_buffer.rs, src/binding.cc, src/lib.rs, src/shared_array_buffer.rs, tests/test_api.rs
It's technically possible to drop the `SharedBuf` returned by `SharedArrayBuffer::new`(and end up with some strange results). Maybe I should rework this to use the internal allocation/backing instead.
=> add v8::SharedArrayBuffer

src/binding.cc, src/isolate.rs, tests/test_api.rs
Expose the following 3 methods:
+ terminate_execution()
+ is_execution_terminating()
+ cancel_terminate_execution()
=> isolate: add termination related methods

src/binding.cc, src/module.rs, tests/test_api.rs
It will be back, but in a different form.
=> Remove rust-abi wrapper for v8::ResolveCallback (#204)

build.rs
To prevent rebuilds due to the compiler being in random directories.
=> Move clang download to target/debug/clang

src/primitives.rs, tests/test_api.rs
This is more consistent with V8's C++ API.
=> Rename new_null() to null() and new_undefined() to undefined() (#216)

src/lib.rs, tests/test_api.rs
- Don't expose empty mod array_buffer_view
- Move v8::platform::new_default_platform() to v8::new_default_platform()
- Move v8::platform::Task to v8::Task
- Move v8::platform::Platform to v8::Platform
=> Reduce nested symbols in API

src/function.rs, src/handle_scope.rs, src/locker.rs, src/scope.rs, src/scope_traits.rs, tests/compile_fail/handle_scope_escape_lifetime.rs, tests/compile_fail/handle_scope_escape_lifetime.stderr, tests/compile_fail/handle_scope_escape_to_nowhere.rs, tests/compile_fail/handle_scope_escape_to_nowhere.stderr, tests/compile_fail/handle_scope_lifetimes.rs, tests/compile_fail/handle_scope_lifetimes.stderr, tests/compile_fail/try_catch_lifetimes.rs, tests/compile_fail/try_catch_lifetimes.stderr, tests/test_api.rs, tests/test_ui.rs
And a lot of scope-related restructuring.
=> Make EscapableHandleScope::escape() inheritable, tighten lifetimes

src/inspector/string_view.rs
Make StringView objects inspectable to make it easier to debug the
V8 inspector's wire protocol.
StringBuffer objects can't be inspected yet because they need a mutable
reference if they want to call `StringBuffer::string()`, which makes
sense because that method calls out to a C++ virtual method that can
modify the object.
For now, instances can be inspected like this:
let mut sb = StringBuffer::create(...);
println!("StringBuffer({})", sb.string().unwrap());
Closes #233
=> Implement fmt::Display for StringView

src/inspector/string_view.rs
Make that easy fix, before I forget...
=> 8-bit StringView uses latin-1 encoding, not UTF-8

src/support.rs, tests/test_api.rs
=> Make SharedRef<T> deref to UnsafeCell<T> instead of T (#242)

src/binding.cc, src/lib.rs, src/object.rs, src/support.rs, tests/test_api.rs
* Rename `Object::new2()` to `Object::with_prototype_and_properties()`.
* Make `Object::with_prototype_and_properties()` take a slice of keys
and a slice of values as arguments, instead of using
`Vec<v8::Local<v8::Name>>` and `Vec<v8::Local<v8::Value>>>`.
* Remove type `MaybeBool` from the public interface. These methods now
return `Option<bool>` instead.
* Fix parameter type mismatches between Rust and C++ APIs.
=> Refactor v8::Object bindings

src/binding.cc, src/lib.rs, src/object.rs, src/string.rs, src/support.rs, tests/test_api.rs
This is more consistent with the C++ API.
=> Rename String::new_empty() to String::empty()

src/binding.cc, src/inspector/client.rs, src/inspector/mod.rs, src/inspector/v8_stack_trace.rs, tests/test_api.rs
This makes it possible to intercept console.log() messages through
the V8 inspector API.
=> Add V8InspectorClientImpl::console_api_message()

src/binding.cc, src/object.rs, tests/test_api.rs
And also Array::creation_context(), Function::creation_context(), etc.,
because they inherit from Object.
=> Add Object::creation_context()

src/inspector/v8_inspector.rs, src/isolate.rs, src/lib.rs, src/scope.rs, src/scope_traits.rs, src/script_compiler.rs, src/snapshot.rs, tests/compile_fail/handle_scope_escape_lifetime.rs, tests/compile_fail/handle_scope_lifetimes.rs, tests/compile_fail/try_catch_lifetimes.rs, tests/test_api.rs
This patch clarifies that v8::Isolate is a single threaded creature
which can only be accessed from other threads in special circumstances.
To ensure optimal operation in Deno, we remove v8::Locker, which ought
to be unnecessary when a thread is dedicated to each Isolate and the
Isolates never move between threads.
There are valid use-cases for v8::Locker, and we hope to address them in
future revisions.
=> Remove v8::Locker

src/binding.cc, src/isolate.rs, src/lib.rs, src/scope_traits.rs, src/script.rs, src/value.rs, tests/compile_fail/handle_scope_escape_to_nowhere.stderr, tests/test_api.rs
The `get_current_context()` and `get_entered_or_microtask_context()`
methods now return `Option<Local<Context>>` to reflect that an isolate
may not have entered any context.
They're also moved from `Isolate` to `struct Entered` because it turns
out that the underlying V8 API calls actually create new local handles,
hence they should only be used inside an active HandleScope.
The `InContext` trait has been removed.
A test exercising `ContextScope` and the `get_*_context()` methods
mentioned above was added.
Closes: #248.
=> Move get_*_context() methods to scope::Entered, remove InContext trait

src/binding.cc, src/function.rs, tests/test_api.rs
This is useful to attach associated data to a function, such that it could be retrieved in the function later
(This is helpful for creating function wrapper around another given JS function without explicitly saving e.g. persistent handles)
=> Add v8::Function::new_with_data to attach associated data

.github/workflows/ci.yml
We don't have many crate deps, but this is free and reduces sccache load slightly.
=> ci: Use github action's cache

.gn
We noticed that the [static lib binaries](https://github.com/denoland/rusty_v8/releases/tag/v0.3.6) were quite large. 176mb for mac/debug.
We aren't sure what exactly is causing this, but I thought by simplifying the `.gn` file we might discover something. With these changes I get:
```
> ls -lh target/debug/gn_out/obj/librusty_v8.a
-rw-r--r--  1 rld  staff   940K Mar 16 18:54 target/debug/gn_out/obj/librusty_v8.a
```
=> Simplify .gn to reduce size of static lib

tools/download_file.py
It just minor fixes to download_file.py. 
I experienced a script aborting while retrying the download. It can be reproduced as follows:
```bash
❯ /usr/local/bin/python  ./tools/download_file.py --url https://httpstat.us/403 --filename test.html
Downloading https://httpstat.us/403...
HTTP Error 403: Forbidden
Retrying in 5 s ...
Traceback (most recent call last):
File "./tools/download_file.py", line 63, in <module>
sys.exit(main())
File "./tools/download_file.py", line 58, in main
DownloadUrl(args.url, f)
File "./tools/download_file.py", line 48, in DownloadUrl
time.sleep(retry_wait_s)
NameError: global name 'time' is not defined
```
=> fix retry process for download_file

src/try_catch.rs, tests/compile_fail/try_catch_exception_lifetime.rs, tests/compile_fail/try_catch_exception_lifetime.stderr, tests/compile_fail/try_catch_message_lifetime.rs, tests/compile_fail/try_catch_message_lifetime.stderr, tests/test_api.rs
According to v8.h, "the returned handle is valid until this TryCatch
block has been destroyed". This is incorrect, as can be demonstrated
with the test below. In practice the return value lives no longer and
no shorter than the active HandleScope at the time these methods are
called. An issue has been opened about this in the V8 bug tracker:
https://bugs.chromium.org/p/v8/issues/detail?id=10537.
```rust
fn try_catch_bad_lifetimes() {
let _setup_guard = setup();
let mut isolate = v8::Isolate::new(Default::default());
let mut hs = v8::HandleScope::new(&mut isolate);
let scope = hs.enter();
let context = v8::Context::new(scope);
let mut cs = v8::ContextScope::new(scope, context);
let scope = cs.enter();
let caught_msg_2 = {
let mut try_catch = v8::TryCatch::new(scope);
let try_catch = …
```
=> Use correct lifetime for TryCatch::exception()/message() return value

src/isolate.rs, tests/test_api.rs
deno no longer depends on these https://github.com/denoland/deno/commit/d4b05dd89e94ed1bba5b24c683da0a895f2ce597
Let's prevent future trouble by not allowing unsafe embedder data.
=> Make get_data and set_data private

build.rs
This is likely to be more user-friendly than the unwrap method.
=> improve error message.

src/binding.cc, src/object.rs, src/value.rs, tests/test_api.rs
I was attempting to rewrite my `mini-v8` crate using `rusty_v8` and saw that a few necessary bindings were missing for my purposes. Thanks for your hard work!
=> Add bindings for `Object`/`Value` items

src/promise.rs, src/scope.rs
Certain callbacks (e.g. `WasmLoadSourceMapCallback`) expect the
embedder to return a local handle (a `Local<String>` in this case), but
do not provide a `Local<Context>` as an argument, nor does it provide
any other argument that we might obtain a context from. This is not
unexpected - WASM execution as such is not tied to a context, and a
`Local<String>` can be created without a context too because it's a
primitive value that has no JavaScript prototype.
=> Add 'CallbackScope<()>' that doesn't assume an entered Context 

Cargo.lock, Cargo.toml, src/binding.cc, src/isolate.rs, src/isolate_create_params.rs, src/lib.rs, tests/test_api.rs
*Applies to https://github.com/denoland/deno/issues/6916*
V8 allows setting the `max_old_generation_size` and `max_young_generation_size` create parameters through a handy helper: https://chromium.googlesource.com/v8/v8/+/e423f0040333dd3ab410b3c6cab5b71a4f75fa6a/include/v8.h#6409
This PR also exposes the methods to register a callback when the limit is reached, so a crash of V8 can be avoided.
=> Allow managing V8 heap limits

Cargo.lock, Cargo.toml, README.md
to exclude https://chromium-review.googlesource.com/c/v8/v8/+/2280100 (0c837e8342dff02294d34d1866c9fcdbd89ffc9f)
experiencing hangs due to this CL in Deno when trying to upgrade to rusty_v8 0.8.0
https://github.com/denoland/deno/pull/6980
=> Downgrade V8 to 8.6.334

src/binding.cc, src/isolate.rs, tests/test_api.rs
This PR adds the bindings for LowMemoryNotification which has been left out of #440.
=> Add support for LowMemoryNotification

src/binding.cc, src/object.rs, src/template.rs, tests/test_api.rs
The rusty_v8 API deviates slightly from the V8 C++ API because the
latter is definitely unsound when you pass in out-of-range indexes.
=> add Object + ObjectTemplate internal field support

build.rs
Previously docs.rs supplied RUSTDOCFLAGS env var to builds, which we
used to skip building/downloading rusty_v8. docs.rs does not allow
network access.
Reference for DOCS_RS: https://docs.rs/about/builds
Failed build: https://docs.rs/crate/deno_core/0.61.0/builds/299870
=> Fix docs.rs detection

src/binding.cc, src/lib.rs, src/support.h, src/support.rs, src/value_deserializer.rs, src/value_serializer.rs, tests/test_api.rs
Hey!
I started working on this issue, meanwhile I'm trying to familiarize myself with the project.
I'm not an experienced Rust developer; so please review my code!
The code I uploaded compiles, but maybe there are still some non-best-practices in the code.
Could you give some feedback before I continue working on this issue?
The current progress:
=> Add ValueSerializer, ValueDeserializer bindings for structured clone in deno

README.md, build.rs
Having rusty_v8 redownload libv8.a every time you blow away target/ is
a good way to blow through your monthly bandwith allotment quickly, to
say nothing about the slowdown of the build.
Fixes #470
=> Make RUSTY_V8_MIRROR understand file:// URLs

src/promise.rs, tests/test_api.rs
Change its return type to `Option<Local<Value>>`. The C++ API
returns `Local<Value>` but that can be an empty handle.
Fixes #491
=> Fix PromiseRejectMessage::get_value()

src/binding.cc, src/function.rs, tests/test_api.rs
This allows object instances to be created from constructor functions. This is useful for instantiating ECMAScript Classes from native code since they cannot be called as functions and must use this `new_instance` path.
=> Add Function::new_instance

src/binding.cc, src/function.rs
It's not necessary to have a separate C++ glue function, it can be
shared with Function::new().
=> Simplify Function::new_with_data()

BUILD.gn, build.rs
This pull request will allow `rusty_v8` to build natively on non-amd64 (`x86_64`) platforms.
The changes in `BUILD.gn` help `src/binding.cc` to pick up compiler flags from V8 configurations (like endianness settings).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/denoland/rusty_v8/514)
=> feat(build): allow native compilation on non-amd64

src/lib.rs
This commit removes `mut` from the `script` variable to avoid the following
warning if used:
```console
25 |   let mut script = v8::Script::compile(scope, code, None).unwrap();
|       ----^^^^^^
|       |
|       help: remove this `mut`
|
= note: `#[warn(unused_mut)]` on by default
warning: 1 warning emitted
```
=> Remove mut from Example in lib.rs

src/data.rs, src/module.rs, tests/test_api.rs
The blanket `std::hash::Hash` impl for instances of `v8::Data` invokes
`v8::internal::Object::GetHash()` but that crashes for `v8::Module`
objects. Use a custom impl that calls `v8::Module::get_identity_hash()`.
Fixes the following runtime assertion:
Refs: https://github.com/denoland/deno/pull/8354#discussion_r522157813
cc @bartlomieju @piscisaureus
=> Fix runtime assert when hashing module object

src/bigint.rs, src/data.rs, src/promise.rs
This reverts commit 58ca728c5f6ef3987f003a261b33deb716cd3173.
<hr>
cc @danbev - your PR passed CI but it's causing `cargo test` to fail locally for me. This is with rustc 1.47.0.
<details>
```
---- src/bigint.rs - bigint::BigInt::new_from_words (line 60) stdout ----
error: unexpected token: `...`
--> src/bigint.rs:61:62
|
3 | (-1)^sign_bit * (words[0] * (2^64)^0 + words[1] * (2^64)^1 + ...)
|                                                              ^^^
|
help: use `..` for an exclusive range
|
3 | (-1)^sign_bit * (words[0] * (2^64)^0 + words[1] * (2^64)^1 + ..)
|                                                              ^^
help: or `..=` for an inclusive range
|
3 | (-1)^sign_bit * (words[0] * (2^64)^0 + words[1] * (2^64)^1 + ..=)
| …
```
=> Revert "Fix rustdoc warnings (#526)"

.github/workflows/ci.yml
Replace deprecated `add-path` and `set-env` with echoing to `$GITHUB_PATH` and `$GITHUB_ENV` respectively.
=> build: upgrade ci script

src/string.rs, src/value.rs, tests/test_api.rs
If it's convenient to have on String objects, then it's convenient to
have on all Value instances.
=> Add Value::to_rust_string_lossy()

examples/hello_world.rs
This commit adds calls to `v8::V8::dispose` and `v8::V8::shutdown_platform`
to the `hello_world.rs` example.
The motivation for adding this is that it was not obvious to me that I
needed to have the Isolate in a separate scope. If there is not, the
platform will have been shutdown before the Isolate's `Drop` function
is called at the end of the function where the scope ends. `Drop` will in
turn call `Dispose` on the V8 Isolate, which calls `Isolate::Deinit`, and
`Deinit` calls `tracing_cpu_profilers.reset()` which will call
`~TracingCpuProfilerImpl` which has a call to `V8::GetCurrentPlatform()`
which will produce the following error:
```console
#
#
#
#
#FailureMessage Object: 0x7fff45b03700Illegal instruction (core dumped)
```
Having an example might safe others some time if they run …
=> Add dispose/shutdown_platform to hello_world

src/symbol.rs, tests/test_api.rs
v8::Symbol is like v8::String and other primitives, it doesn't need an
active v8::Context.
See also #549.
=> Make Symbol work with context-less HandleScope

tests/test_api.rs
This commit fixes a typo in the `send_notification` function which can be
seen when running the following test:
```console
$ cargo test --test test_api -- --test \
inspector_schedule_pause_on_next_statement --nocapture
Finished test [unoptimized + debuginfo] target(s) in 0.05s
Running target/debug/deps/test_api-2dce272ff86e969e
running 1 test
send_response call_id 1 message
{"id":1,"result":
{"debuggerId":"6374278651496261962.-7730398402173275062"}
}
send_notificatio message {...
```
=> Fix typo in send_notification print statement

src/V8.rs, src/binding.cc, tests/test_api.rs
This commit suggests adding a usage string which can be passed to V8
when setting the command line flags. If the `--help` flag is specified
then the usage string will be printed before the V8 options.
The motivation for this would be to enable embedders of rusty_v8 to
pass their own usage string and have their usage printed before V8's
options.
For example:
```console
Usage: binaryname --startup-src=file
SSE3=1 SSSE3=1 SSE4_1=1 SSE4_2=1 SAHF=1 AVX=1 FMA3=1 BMI1=1 BMI2=1
The following syntax for options is accepted (both '-' and '--' are ok):
--flag        (bool flags only)
--no-flag     (bool flags only)
--flag=value  (non-bool flags only, no spaces around '=')
--flag value  (non-bool flags only)
--            (captures all remaining args in JavaScript)
Options:
...
```
=> Add set_flags_from_command_line_with_usage fn

src/private.rs, tests/test_api.rs
v8::Private is like v8::String and other primitives, it doesn't need an
active v8::Context.
=> Make Private work with context-less HandleScope

src/binding.cc, src/function.rs, src/template.rs, tests/test_api.rs
v8::Function and v8::FunctionTemplate have a lot of options that can be
configured. The builder() associated functions on those types help with
that.
<hr>
cc @ry - this is more groundwork for fast API calls.
cc @devsnek - I'll concede that I was wrong and you were right. 🙂
=> Add FunctionBuilder

Cargo.toml
Ref: [include/exclude in Cargo manual](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields).
This should fix the problem of `.gn` and other files being missing from the crate, though I'm not sure how I can test that (haven't worked much with crates).
`BUILD.gn` _is_ there however, so I wonder if this points to a bug in Cargo? I'm hoping that the explicit `include` setting will help the case here.
```bash
shm/vendor/rusty_v8 is 📦 v0.14.0 via 🦀 v1.47.0
❯ ls -lrath
total 436K
-rw-r--r--   1 avindra users 2.0K Dec 19 04:07 Cargo.toml
-rw-r--r--   1 avindra users 5.5K Dec 19 04:07 Cargo.lock
-rw-r--r--   1 avindra users 1.2K Dec 19 04:07 BUILD.gn
drwxr-xr-x   3 avindra users   60 Dec 19 04:07 base/
-rw-r--r--   1 avindra users  10K Dec 19 04:07 build.rs …
```
=> Use "include" to specify kept files

README.md, build.rs
This should allow people to build without explicitly setting `GN` and `NINJA` env vars.
If the tool(s) are detected, the build will continue without trying to download the binaries.
=> improve ninja/gn detection

src/isolate.rs, tests/test_api.rs
This commit adds following methods to Isolate:
- terminate_execution
- cancel_terminate_execution
- is_execution_terminating
Addresses following TODOs from `deno_core`:
- https://github.com/denoland/deno/blob/b15539587e7cf6b67c2ae7d4dc39901634bf6bd5/core/runtime.rs#L607-L610
- https://github.com/denoland/deno/blob/b15539587e7cf6b67c2ae7d4dc39901634bf6bd5/core/runtime.rs#L616-L618
- https://github.com/denoland/deno/blob/b15539587e7cf6b67c2ae7d4dc39901634bf6bd5/core/runtime.rs#L641-L643
=> Add methods for termination to Isolate

Cargo.toml
This reverts commit e057d096fd67bd273bb261d0ef2fdeb65ab9b815.
That commit caused failure of `cargo publish`:
```
Run cargo publish -vv
Updating crates.io index
warning: both package.include and package.exclude are specified; the exclude list will be ignored
```
=> Revert "Use "include" to specify kept files (#559)"

src/binding.cc, src/function.rs, src/isolate.rs, src/lib.rs, src/wasm.rs, tests/test_api.rs
Add the hook necessary to implement `WebAssembly.compileStreaming()`.
Fixes #556
cc @caspervonb
=> Add Isolate::set_wasm_streaming_callback()

src/V8.rs, tests/test_api.rs
This commit removes the set_flags_from_command_line_with_usage and puts
it in an example code section instead.
The motivation for doing this is that the test output currently contains
the usage string and all the V8 options which creates a lot of output
when the tests is run regardless if --nocapture is used or not.
=> Remove set_flags_from_command_line_with_usage test

src/binding.cc, src/lib.rs, src/script.rs, src/unbound_script.rs, tests/test_api.rs
I'm working on [a project](https://github.com/losfair/rusty-workers) where I want to reuse the same `Isolate` with different `Context`'s and cache compiled scripts.
rusty_v8 currently only exposes `Script` that is bound to a specific context, and adding conversion to and from `UnboundScript` allows using a compiled script from different contexts.
=> Add Script::get_unbound_script and UnboundScript::bind_to_current_context.

src/lib.rs, tests/test_api.rs
Without it, v8::String::write_utf8() is pretty much unusable.
=> Expose v8::WriteOptions

Cargo.toml
The only file that is actually needed is tools/clang/scripts/update.py
and that's already explicitly excluded from the exclude list.
Shrinks the (unpacked) crate size by 2.4 MB.
=> Exclude tools/clang from publish

src/binding.cc, src/isolate.rs, tests/test_api.rs
Refs: https://github.com/denoland/deno/issues/7644
=> Add Isolate::set_prepare_stack_trace_callback()

.github/workflows/ci.yml
Doesn't work correctly on windows.
This reverts commit c623c451b1d04f262be030754a164ac949933544.
=> Revert "upgrade sccache (#592)"

src/icu.rs
Rustdoc interprets code snippets as Rust unless told otherwise.
Tell it otherwise because this particular snippet is C++.
=> Fix doc comment in src/icu.rs

src/value_deserializer.rs, tests/test_api.rs
The return value should have the lifetime of the context, not the
deserializer.
Fixes #607.
=> Fix ValueDeserializer::read_value() lifetime

Cargo.toml
Maybe fixes https://github.com/denoland/rusty_v8/issues/610 
I'm not sure how I can test this without uploading to crates.io. Suggestions?
=> include v8/tools/gen-v8-gn.py in package

.gitmodules, Cargo.lock, Cargo.toml
Here is the hack: https://github.com/denoland/icu/commit/28b0e9ea59878fdd1682593be2ac489a6a6bbb21
Note the size of [0.18.0](https://crates.io/crates/rusty_v8/0.18.0)  on crates.io  is 19.5 MB. This change will bring that back down to a reasonable level.
=> Hack ICU build scripts so we don't have to depend on icudata file

.github/workflows/ci.yml
This PR:
-  re-enables `aarch64-unknown-linux-gnu` builds
- Updates the workflow to only use `ubuntu-latest-xl` on `denoland/rusty_v8`, since this runner is not available in regular repos (just to make forking a bit easier).
This PR doesn't do anything different to #589, and I suspect the issue lies with `denoland/rusty_v8`'s cache, since simply re-enabling the `aarch64-unknown-linux-gnu` builds "just worked" in my fork.
🤞
=> Re-enable aarch64 builds

src/binding.cc, src/lib.rs, src/module.rs, src/script_compiler.rs, src/support.rs, src/unbound_module_script.rs, src/unbound_script.rs, tests/test_api.rs
This pull request exposes the V8 `CachedData` interface and supports:
- Creating code cache from `UnboundScript` and `UnboundModuleScript`.
- Creating `Source` with cached code.
=> Add code cache API.

build.rs
Since we download `x86_64` `ninja` and `gn` on M1 macs `gn` incorrectly targets `x86_64` by default.
This codifies [ry's workaround](https://github.com/denoland/rusty_v8/issues/520#issuecomment-740190036) so that `V8_FROM_SOURCE=1 cargo build --release` does the right thing out of the box, no surprises.
I hadn't checked the comments and all the threads, so I ended up "wasting" a decent amount of time building versions I couldn't link against, when wanting to test local changes with other crates. So hopefully this saves other contributors time.
=> build: patch GN's host_cpu detection on Apple Silicon

src/binding.cc, src/script_compiler.rs, tests/test_api.rs
- Expose `ScriptCompiler::Compile` and `ScriptCompiler::CompileUnboundScript`.
- Make the `origin` parameter on `Source` constructor optional.
=> Add more ScriptCompiler APIs.

src/binding.cc, src/string.rs, tests/test_api.rs
This PR partially fixes #636, by adding support for external static rust strings.
Rust doesn't have utf16 (or two-byte string) literals, so we could shorten the name in this static case, i.e:
```rust
v8::String::new_external_static()
instead of
v8::String::new_external_onebyte_static()
```
We could support non-static external strings too, but I'm not sure we want to encourage that.
=> Initial support for external v8 strings

src/binding.cc, src/lib.rs, src/platform.rs, tests/test_single_threaded_default_platform.rs
This is a v8::Platform implementation that doesn't spawn additional
threads. Useful in combination with the --single_threaded flag.
=> Add new_single_threaded_default_platform()

src/binding.cc, src/module.rs
v8::Location is the size of two ints, not the size of one size_t.
`2 * sizeof(int) == sizeof(size_t)` on 64 bits architectures but not on
32 bits architectures.
Fixes #667.
=> Fix bad assumption in static_assert

.github/workflows/update-v8.yml, tools/auto_update_v8.ts
This commit adds a nightly job that updates V8 to the lkgr on the tracked
V8 release. It will open at most one PR. As long as this PR is still open the
nightly job will sync it, instead of opening another PR. If no autoroll PR is
open, one will be created.
=> chore: set up v8 autoroll script

src/isolate.rs, src/support.rs
makes a few warnings go away.
```
warning: trait objects without an explicit `dyn` are deprecated
--> src/isolate.rs:418:13
|
418 |     let r = Any::downcast_ref::<T>(&**b).unwrap();
|             ^^^ help: use `dyn`: `<dyn Any>`
|
= note: `#[warn(bare_trait_objects)]` on by default
warning: trait objects without an explicit `dyn` are deprecated
--> src/isolate.rs:425:13
|
425 |     let r = Any::downcast_mut::<T>(&mut **b).unwrap();
|             ^^^ help: use `dyn`: `<dyn Any>`
warning: trait objects without an explicit `dyn` are deprecated
--> src/support.rs:411:8
|
411 |     if Any::is::<Concrete>(&value) {
|        ^^^ help: use `dyn`: `<dyn Any>`
warning: 3 warnings emitted
Finished dev [unoptimized + debuginfo] target(s) in 2.29s
```
Signed-off-by: Nicky Sielicki …
=> add explicit 'dyn's in a few spots

.gitmodules, .gn, README.md, src/icu.rs
We are floating a revert of v8/v8@7f9d7f0 because of the issue described
in #694.
=> Upgrade V8 to 9.2.230.10

src/binding.cc, src/string.rs, tests/test_api.rs
=> Add missing methods for one- and two-byte strings.

.gn
Enable the v8_use_siphash flag. This flag is enabled since Node.js
v11.12.0 (2019-03-15), see linked PR, release notes, and the blog post
detailing the attack.
Ref: https://github.com/nodejs/node/pull/26367
Ref: https://nodejs.org/gl/blog/release/v11.12.0/
Ref: https://darksi.de/12.hashwick-v8-vulnerability/
=> build: enable v8's siphash for hash seed creation

src/value_deserializer.rs, src/value_serializer.rs, tests/test_api.rs
They are only useful in read_host_object and write_host_object if
the helpers are available as a mut ref.
=> fix: pass serializer helpers as mut refs

src/binding.cc, src/template.rs, tests/test_api.rs
Adds the PrototypeTemplate, Inherit, ReadOnlyPrototype and RemovePrototype methods to the FunctionTemplate.
Closes #716 
I currently don't have tests written for the Inherit, ReadOnlyPrototype and RemovePrototype methods, since they just call their C++ counterparts without any additional rust code so I didn't feel the need to test them.
=> Adds PrototypeTemplate and other small methods to the FunctionTemplate

examples/hello_world.rs, examples/process.rs, examples/shell.rs, src/V8.rs, src/binding.cc, src/lib.rs, src/platform.rs, src/scope.rs, tests/slots.rs, tests/test_api.rs, tests/test_api_entropy_source.rs, tests/test_api_flags.rs, tests/test_platform_atomics_pump_message_loop.rs, tests/test_single_threaded_default_platform.rs
Added `pump_message_loop` and `run_idle_tasks` to `v8::Platform`.
The `GLOBAL_PLATFORM` now manages the active platform.
=> platform: pump_message_loop, run_idle_tasks, GLOBAL_PLATFORM

.github/workflows/ci.yml, Cargo.toml
Fixes #721
```
-rw-r--r--  1 ry  staff    14M Jul  1 17:06 target/package/rusty_v8-0.24.0.crate
```
This was the only workaround I could find. Should still fit under the 20M limit for crates.io
We should also add a CI job that tests "cargo package".
=> Include ICU file in crate

.gn
=> perf: disable siphash, v8 now uses 64bit hash seed

.github/workflows/ci.yml
denoland/rusty_v8 uses ubuntu-latest-xl, which is still at 18.04. Use a
compatible image for third-party forks.
Third-party builds failed trying to install the gcc-5 cross-compiler
toolchain, which indeed is no longer available in 20.04.
Fixes #733.
=> chore: downgrade to ubuntu-18.04 ci image

tests/test_api.rs
The test started a new thread that slept for a bit, then terminated the
isolate, assuming that the delay was long enough for the isolate and the
context to get fully initialized. It wasn't.
Fixes #710.
=> fix: remove race in terminate_execution test

.github/workflows/ci.yml, build.rs
Upgrades Rust to 1.54.0 and applys clippy's fixes.
=> chore: upgrade Rust to 1.54.0

tests/test_api.rs
Serializing `new String("")` requires that the wire format header is
written, otherwise V8 assumes an incompatible legacy wire format when
deserializing.
=> chore: test String object serialization

src/binding.cc, src/data.rs, src/lib.rs, src/wasm.rs, tests/test_api.rs
`v8::CompiledWasmModule` is a representation of a compiled WebAssembly module, which can be shared by multiple `v8::WasmModuleObject`s.
Closes #759.
=> feat: Add `v8::CompiledWasmModule`

src/binding.cc, tests/test_api.rs
Best case, it produces serialized output that cannot be deserialized.
Worst case, it hits this assert in V8:
=> Throw DataCloneError if SAB cannot be cloned

src/binding.cc, src/function.rs, tests/test_api.rs
Add bindings for v8::Function::GetName() and v8::Function::SetName()
=> feat: Function::get/set_name()

src/handle.rs, src/scope.rs, tests/test_api.rs
This also adds a deprecated `Global::get()` method to avoid unnecessarily breaking a lot of users code.
cc @espindola
=> Rename Handle::get() to Handle::open() instead

build.rs
This avoids constant rebuilds when alternating between running
$ cargo build
$ cargo run <something that runs cargo build>
Since the second command will see these environment variables set
during the logic deciding if build.rs should be rerun or not.
Since these are cargo specific variables, hopefully cargo already does
the right thing without our help.
=> Ignore environment variables set by cargo

src/function.rs, tests/test_api.rs
This makes the callbacks themselves less restrictive. A test is added
the would fail to compile before.
=> Make lifetime in FunctionCallback more restrictive

src/array_buffer.rs, tests/test_api.rs
The pointer returned by `BackingStore::data` might be null if the backing store has zero length, but the return type `*mut c_void` does not force the user to consider this case. This change makes the return type `Option<NonNull<c_void>>`, which is semantically equivalent, but which forces users of the API to handle the `None` case.
This is a breaking API change.
=> refactor: Have `BackingStore::data` return `Option<NonNull<c_void>>`

tests/test_concurrent_isolate_creation_and_disposal.rs
This patch includes a test for this issue.
The V8 patch is intentionally left simple to avoid merge conflicts in
the future. To be landed upstream, the `unwindinfo_use_count_` would
probably have to be made non-atomic and we'd have to add a cctest.
Upstream bug: https://bugs.chromium.org/p/v8/issues/detail?id=12393
Fixes: #714
=> v8: fix segfault during concurrent isolate creation/disposal on Windows

src/array_buffer.rs, tests/test_api.rs
This results in a segmentation fault when dropping a `BackingStore` constructed through `ArrayBuffer::new_backing_store_from_boxed_slice` from an empty slice, since empty boxed slices can be invalid pointers, but `Box<c_void>` can't.
Fixes #849.
=> fix: `backing_store_deleter_callback` drops a `Box<c_void>`, not a `Box<[u8]>`

src/binding.cc, src/exception.rs, tests/test_api.rs
I originally added this binding to experiment with stacktrace stitching in `deno`, but as I suspected it's way too slow ...
Might be good to add for completeness sake or other use-cases ...
=> feat: v8::StackTrace::CurrentStackTrace() bindings

.cargo/config.toml, .github/workflows/ci.yml, .gitignore, Cargo.lock, Cargo.toml, Cross.toml, Dockerfile, build.rs, examples/android_fractal.js, examples/android_fractal.rs, src/wasm.rs, tests/test_api.rs, tests/test_concurrent_isolate_creation_and_disposal.rs, tests/test_ui.rs
Adds support for `aarch64-linux-android`.
Continuation of #270 with testing and build cache enabled.
Also adds a little frame buffer example (`example/android_fractal.rs`):
<image src="https://user-images.githubusercontent.com/34997667/147415649-bd9b1a45-bab9-4e15-b6fa-144b3c49ba6e.png" width=246 height=533 />
=> add support for `aarch64-linux-android`

.gn
It was disabled upstream¹, citing a minimal size bump of ~400 kB.
However Deno got ~24 MB bigger, which is unacceptable.
¹ https://chromium-review.googlesource.com/c/v8/v8/+/3275554
=> fix: re-enable v8 snapshot compression

.gn
It turns out that the embedder can selectively compress snapshots,
resulting in better startup performance and a smaller binary size.
See https://github.com/denoland/deno/pull/13320.
=> Disable snapshot compression on all platforms

src/binding.cc, src/object.rs, tests/test_api.rs
Support v8::Map operations (`new`, `clear`, `get`, `set`, `has`,
and `delete`).
=> Add v8::Map bindings

.github/workflows/ci.yml
Fails regularly and inexplicably even though installing and starting
sscache works just fine:
/home/runner/work/_temp/c2b88417-fdca-4378-b8c3-66cea7ddc094.sh:
line 1: sccache: command not found
It's probably a path issue but as there doesn't seem to be much point in
stopping it explicitly, I'm opting to simply remove that CI build step
altogether.
=> chore: remove "stop sscache" ci step

src/binding.cc, src/object.rs, tests/test_api.rs
This allows making objects frozen or sealed from rust code. This is
useful to control mutations that are allowed to happen in JS on the
given object.
=> Add support for v8::Object.set_integrity_level

src/script_compiler.rs, tests/test_api.rs
The `cached_data` property of `Source` is optional, so reading the value
should return `Option<&CachedData>`.
Fixes #884
=> Make v8::script_compiler::Source.get_cached_data return Option

src/binding.cc, src/external_references.rs, src/string.rs, src/typed_array.rs, tests/test_api.rs
Those are useful for pre-checking buffer sizes before attempting to create
a new String or typed array (or ArrayBuffer). Also useful for pre-allocating
possibly large chunks of memory safely.
=> Add bindings for String::kMaxLength / TypedArray::kMaxLength

src/function.rs, src/template.rs, tests/test_api.rs
Unblocks https://github.com/denoland/deno/pull/13861
The MapFnTo trait is quite contrived and can't be turned into a trait object thus blocking declarative ops
=> feat: new_raw APIs avoiding MapFnTo path

Cargo.toml
The latest ICU update increased the file size of the crate to above 20 MB again. This commit removes an ICU data file from the package that is unneeded for the build.
I tested the build still works by doing:
```
$ export V8_FROM_SOURCE=1
$ cargo package
```
And it still works.
=> Ignore more unnecessary ICU data

Cargo.toml, build.rs
The feature `use_custom_libcxx` is enabled by default. If the feature `use_custom_libcxx` is disabled the crate will link the system libcxx instead.
Once this is merged and released, a followup PR will be created for:
* `deno_core`, so it re-exposes the feature flag. Thus allowing `deno_core` users to disable custom libcxx using `default_features=false`.
* `serde_v8`, so it depends on `rusty_v8` with `default_features=false`.
Closes #920
=> Add feature flag for using custom libcxx

src/array_buffer.rs, tests/test_api.rs
useful for https://github.com/denoland/deno/pull/13633
which currently uses a "hack" to create externally backed array buffers: https://github.com/littledivy/deno/blob/4fb9b90da6bcab9690ba2113083520f709a0b636/cli/napi/js_native_api.rs#L312
also needed to make zero-copy arraybuffers (returned from FFI. there is UnsafePointerView#getArrayBuffer, which currently copies)
=> feat: ArrayBuffer::new_backing_store_from_ptr

src/array_buffer.rs, src/shared_array_buffer.rs, tests/test_api.rs
So we can avoid `.into_boxed_slice()` calls which may require a (costly) memmove when instantiating from a `Vec`
- In theory, dropping & deallocating a Vec depends on its layout, which is not fully restored in the deleter (since we simplify len=cap, which may be untrue)
- We could pass the cap in the deleter_data void ptr and transmute to `usize`
- But after double-checking rust's src the GlobalAllocator/SystemAllocator `dealloc` does not depend on layout and simply calls `free` (or `HeapFree`) as I expected
- So in practice this shouldn't be an issue
=> feat: v8::ArrayBuffer::new_backing_store_from_vec

.gn, src/binding.cc, src/context.rs, tests/test_api.rs
Add support for `Context::SetPromiseHooks` for follow-up works of https://github.com/denoland/deno/pull/8209.
=> feat: add binding for Context::SetPromiseHooks

src/binding.cc, src/handle.rs, src/isolate.rs, src/lib.rs, tests/test_api.rs
Just a strawperson proposal to test out the waters. The Discord conversation mentioned storing the callbacks in the isolate annex (or something), but doing it with pinned boxes seems easier to implement. We can still change it to use the annex, of course.
Closes #861.
=> Weak handles and finalizers

src/binding.cc, src/template.rs, tests/test_api.rs
This adds bindings for the `FunctionTemplate->InstanceTemplate()` method, which may be used to get a handle to the object template used when the function is used as a constructor. 
I added a test to ensure you can set internal fields and read them from the constructed objects later.
=> add FunctionTemplate::instance_template binding

build.rs
To make it easier to debug builds, run `gn args $GN_OUT_DIR --list`
=> print gn args --list

src/inspector.rs, src/scope.rs, src/value_deserializer.rs, src/value_serializer.rs
While reviewing the code in this repo, I found questionable uses of `MaybeUninit` that go against what is said in the docs:
> It is up to the caller to guarantee that the MaybeUninit<T> really is in an initialized state. Calling this when the content is not yet fully initialized causes **immediate undefined behavior.**
<sub>[MaybeUninit::assume_init](https://doc.rust-lang.org/stable/std/mem/union.MaybeUninit.html#safety)</sub>
https://github.com/denoland/rusty_v8/blob/9b2d8c68ade1ad4f935534dbdd610f47c80f7b64/src/scope.rs#L1535-L1545
There is even a lint that is explicitly disabled here that says that `MaybeUninit::<[usize; 3]>::uninit().assume_init()` may be instant UB and is better avoided.
So, instead of storing a `[usize; 3]` in an uninitialized state, I think the right thing to do …
=> Fix misuse of `MaybeUninit` and avoid refs to uninit memory

.gn
Enables the use of `set_internal_field` on v8::Promise. Can be used to track/store `promiseId` associated with the Promise.
=> Set `v8::Promise` internal field count to 1

src/binding.cc, src/function.rs, tests/test_api.rs
This commit adds bindings to `v8::ReturnValue::Set` 
variants for specific types.
Eg: `set_int32` has a fast path for SMI integers.
=> Add type specialized setters for v8::ReturnValue

src/function.rs, src/wasm.rs, tests/test_api.rs
This commit makes `FunctionCallbackArguments::from_function_callback_info`
and `ReturnValue::from_function_callback_info` public API.
Currently, there is no way to use FunctionCallbackArguments 
and ReturnValue from Function::builder_raw.
=> Expose `from_function_callback_info`

build.rs
This was added for debugging purposes back in https://github.com/denoland/rusty_v8/pull/962 but was removed in an unrelated change ([Upgrade V8 to 10.3.174.3](https://github.com/denoland/rusty_v8/commit/2f189e1668a33e96e1e5a431c234849e6e20834b#diff-d0d98998092552a1d3259338c2c71e118a5b8343dd4703c0c7f552ada7f9cb42L220)). 
Printing the gn args is verbose but helps debugging. Being able to examine the args used in, for example, the homebrew build without having to repeat the build saves time.
=> Add back gn args --list on build

src/binding.cc, src/number.rs, tests/test_api.rs
Adds bindings for `Uint32` and `Int32` classes to directly access the `u32` / `i32` value without going through the `Integer` class' `Value` method.
The difference in V8 code for proper SMIs, which these should always be, is only the return type. Effectively then the current call path does:
> int -> int64_t -> u32 / i32
whereas the new callpath is then
> int -> int32_t -> u32 / i32
This'll maybe save an instruction or two.
Closes #1027.
=> feat: Add Uint32 / Int32 Value method bindings

src/binding.cc, src/script_compiler.rs
Hello, thank you for rusty_v8! Building for the 32-bit `armv7-unknown-linux-musleabihf`
target gives the following compilation error due to some assumptions about the
layout of the C++ `v8::ScriptCompiler::Source` class:
```
../../../../src/binding.cc:43:50: error: static assertion failed: Source size mismatch
43 | static_assert(sizeof(v8::ScriptCompiler::Source) <= sizeof(size_t) * 8,
```
This assert matches the corresponding Rust struct definition `pub struct Source([usize; 8]);`
on 64-bit platforms where the size of the fields plus padding mean
`sizeof(v8::ScriptCompiler::Source) == 64`.
However on 32-bit ARM `sizeof(v8::ScriptCompiler::Source) == 36` but
`size_of::<[usize; 8]>() == 32`.
This PR updates the layout of the Rust `v8::script_compiler::Source` struct
to match [that of the …
=> Fix compilation for 32-bit targets

.gitmodules, .gn
Deno does its own snapshot compression using lz4 and zstd, so no need to
build zlib into V8. See https://github.com/denoland/deno/pull/13320
=> Remove zlib dependency

build.rs
Building rusty_v8 for targets lacking a binary `librusty_v8.a`, for example `aarch64-unknown-linux-musl`, currently fails with a confusing error message:
```
error: failed to add native library $PWD/target/aarch64-unknown-linux-musl/debug/gn_out/obj/librusty_v8.a: file too small to be an archive
```
This is because build.rs falls back to use of curl after `download_file.py` fails. The curl command is currently ignoring HTTP error statuses and writes the HTTP error message to librusty_v8.a:
```
% cat $PWD/target/aarch64-unknown-linux-musl/debug/gn_out/obj/librusty_v8.a
Not Found
```
This PR adds curl's `-f` flag to the command arguments which results in a more useful error message, as well as not writing an invalid `librusty_v8.a`.
=> Fix creation of invalid librusty_v8.a

src/property_attribute.rs, tests/test_api.rs
* `property_attribute` previously had an addition operator overload which doesn't make much sense in comparison to the corresponding V8 enumeration. This changes that to a bitor overload.
* There was an edge case where `READ_ONLY (1) + READ_ONLY (1) + DONT_ENUM (2)` would evaluate to `DONT_DELETE (4)` instead of `READ_ONLY + DONT_ENUM` because of addition. This change also fixes that and adds a test for that case.
Signed-off-by: Darshan Sen <raisinten@gmail.com>
cc @bnoordhuis since this was added in https://github.com/denoland/rusty_v8/pull/228
=> fix: `property_attribute` operator

src/array_buffer.rs, src/binding.cc, tests/test_api.rs
https://v8.github.io/api/head/classv8_1_1ArrayBuffer.html
> More efficient shortcut for [GetBackingStore()](https://v8.github.io/api/head/classv8_1_1ArrayBuffer.html#aaa29e281f94990cbf0a5484140fffb50)->Data(). The returned pointer is valid as long as the [ArrayBuffer](https://v8.github.io/api/head/classv8_1_1ArrayBuffer.html) is alive.
=> Add `v8::ArrayBuffer::Data`

build.rs
Ensure allocation of typed arrays and arraybuffers always goes through the embedder's ArrayBufferAllocator, otherwise small buffers get moved around by the garbage collector but embedders normally want them to have fixed addresses.
Refs #1068.
=> Build with v8_typed_array_max_size_in_heap=0

src/fast_api.rs, tests/test_api.rs
Upstream CL: https://chromium-review.googlesource.com/c/v8/v8/+/3844662
Fast API calls invalidly used plain `v8::Value` for the `options.data` representation. This effectively meant that only SMI data could successfully pass through to fast calls.
The issue has now been fixed upstream, meaning that the `options.data` representation has become `v8::Local<v8::Value>`. This PR should then unblock downstream PR https://github.com/denoland/deno/pull/15527
=> fix(fastcall): Fix `options.data` representation

Cargo.toml, benches/function.rs
```
> cargo bench -- function
19.1 ns per run 52.4 million ops/sec → new_
18.4 ns per run 54.2 million ops/sec → new_raw
14.4 ns per run 69.4 million ops/sec → new_set_uint32
6.7 ns per run 149.3 million ops/sec → new_raw_set_uint32
2.7 ns per run 369.0 million ops/sec → new_fast
```
=> Add benchmarks for V8 native function calls

src/string.rs
This commit allows writing data to an uninitialized buffer.
Related:
+ https://github.com/denoland/deno/issues/15020
=> feat: add String::write_utf8_uninit

src/binding.cc, src/isolate.rs, src/scope.rs, tests/test_api.rs
Before (on a MacBook Pro M1 2021):
```
Running function_overhead ...
18.0 ns per run 55.5 million ops/sec → new_
18.4 ns per run 54.5 million ops/sec → new_raw
13.5 ns per run 74.1 million ops/sec → new_set_uint32
8.8 ns per run 113.4 million ops/sec → new_raw_set_uint32
2.7 ns per run 366.3 million ops/sec → new_fast
Running primitives ...
15.0 ns per run 66.7 million ops/sec → undefined_from_scope
7.6 ns per run 131.8 million ops/sec → undefined_from_isolate
```
After:
```
Running function_overhead ...
15.1 ns per run 66.2 million ops/sec → new_
15.1 ns per run 66.1 million ops/sec → new_raw
11.5 ns per run 87.2 million ops/sec → new_set_uint32
6.8 ns per run 146.6 million ops/sec → new_raw_set_uint32
2.7 ns per run 367.6 million ops/sec → new_fast
Running primitives ...
12.2 ns per run …
```
=> perf: optimize scope construction and `Isolate::get_slot/set_slot()`

.gitmodules, .gn
This reverts commit 169d5d6ea00ddb12e09ae032004bbb04ad816c93.
This commit caused the startup time in Deno to go from 17ms to 23ms.
=> Revert "Remove zlib dependency (#1058)"

src/array_buffer.rs, src/binding.cc, tests/test_api.rs
This PR adds `ArrayBuffer::was_detached()`.
While there's no `WasDetached` method on [`ArrayBuffer`](https://v8.github.io/api/head/classv8_1_1ArrayBuffer.html), while going through the code I noticed there is one in [`JSArrayBufferView`](https://chromium.googlesource.com/v8/v8/+/refs/heads/main/src/objects/js-array-buffer.h#259) that we could use.
Currently, Deno has no reliable way to check if an ArrayBuffer was detached. With this commit, we'll be able to make Streams and `structuredClone` spec-compliant.
=> feat: add ArrayBuffer::was_detached()

benches/function.rs, src/binding.cc, src/function.rs, src/isolate.rs, src/scope.rs, src/wasm.rs, tests/test_api.rs
```
Running function_overhead ...
15.1 ns per run 66.2 million ops/sec → new_
15.2 ns per run 65.7 million ops/sec → new_raw
11.2 ns per run 89.7 million ops/sec → new_set_uint32
6.8 ns per run 147.1 million ops/sec → new_raw_set_uint32
2.7 ns per run 367.6 million ops/sec → new_fast
Running primitives ...
11.7 ns per run 85.3 million ops/sec → undefined_from_scope
7.5 ns per run 133.2 million ops/sec → undefined_from_isolate
```
```
Running function_overhead ...
14.6 ns per run 68.7 million ops/sec → new_
14.7 ns per run 67.9 million ops/sec → new_raw
10.9 ns per run 91.7 million ops/sec → new_set_uint32
6.8 ns per run 147.9 million ops/sec → new_raw_set_uint32
2.7 ns per run 367.6 million ops/sec → new_fast
Running primitives ...
11.2 ns per run 89.5 million ops/sec → …
```
=> perf: optimize FunctionCallbackInfo and PropertyCallbackInfo methods

src/array_buffer.rs, src/binding.cc, tests/test_api.rs
This method, introduced in V8 10.9, makes it so an `ArrayBuffer` object is impossible to detach unless a specific detach key is passed to the `detach` method. Such `ArrayBuffer`s still count as detachable as per the `ArrayBuffer::is_detachable` method, but otherwise behave much like WebAssembly memories.
=> Add `ArrayBuffer::set_detach_key`

src/binding.cc
In #1103, the `ArrayBuffer::was_detached` method was added to rusty_v8 to fill a gap in the C++ API, and it was implemented using the internal `v8::Utils::OpenHandle`. Since then, a `WasDetached` method was added to `ArrayBuffer` in V8 10.9. This PR updates the implementation to use that.
=> Update `ArrayBuffer::was_detached` to not use `OpenHandle`

src/array_buffer.rs, tests/test_api.rs
The pointer returned by `ArrayBuffer::data` might be null if the backing store has zero length, but the return type `*mut c_void` does not force the user to consider this case. This change makes the return type `Option<NonNull<c_void>>`, which is semantically equivalent, but which forces users of the API to handle the `None` case.
This PR is the `ArrayBuffer` counterpart to #817.
This is a breaking API change.
=> refactor: Have `ArrayBuffer::data` return `Option<NonNull<c_void>>`

Cargo.lock, Cargo.toml, src/V8.rs, src/context.rs, src/external_references.rs, src/fast_api.rs, src/handle.rs, src/icu.rs, src/isolate.rs, src/isolate_create_params.rs, src/object.rs, src/script_compiler.rs, src/string.rs, src/support.rs, src/template.rs, src/typed_array.rs
The main goal of this PR is to remove dependencies with functionality that is already present in the `std` or the crate.
Only size_t needs to be defined like was done with the `intptr_t` type before.
Also unifies the usage of `std::os::raw` types that where already defined in the support module and used in other parts of the crate.
=> Remove libc dependency.

src/binding.cc, src/inspector.rs, tests/test_api.rs
Some clients like VSCode expect that `auxData` will be set to `{"isDefault": true/false}`. I think this stems from how Node integrates with debuggers. I confirm that it fixes one of the problem where inspector doesn't disconnected in VSCode after program finishes.
=> Add 'aux_data' to v8::Inspector::contextCreated()

src/fast_api.rs
I'll have to do another release.
=> Fix length type of FastApiOneByteString

.github/workflows/release.yml, README.md
This workflow will bump a version and create a tag which will kick-off another
build that will build release binary archives and create a GH release.
Maintainer is still responsible for building artifacts on M1 mac.
=> ci: add "release" action workflow

src/binding.cc, src/inspector.rs, tests/test_api.rs
Revival of https://github.com/denoland/rusty_v8/pull/717
Closes https://github.com/denoland/rusty_v8/issues/715
=> feat: v8::Inspector::exception_thrown, v8::Inspector::create_stack_trace

.github/workflows/ci.yml
Hopefully this fixes the problem that caused abort of v0.59.0 release 🤞
=> ci: update release action

rust-toolchain.toml, src/external.rs
I tested `lint` in local computer(windows 11), but it was not passed test case in my repo...
TBH, I am not sure I can update the toolchain to `rust 1.66.0`.
=> chore: update to Rust 1.66.0

.github/workflows/ci.yml
Updates python to 3.11.x, python setup to v3, cache to v3, and rust to version 1.66.1
=> ci: update python, python setup, cache, and rust version

.gn
Enabling the shared read-only heap comes with a restriction that all
isolates running at the same time must be created from the same snapshot.
This is problematic for Deno, which has separate "runtime" and "typescript
compiler" snapshots, and sometimes uses them both at the same time.
=> build: turn off `v8_enable_shared_ro_heap` flag again

src/handle.rs
This change updates the documentation of `Weak::with_finalizer` to reflect the fact that the previous stricter guarantees were dropped in #1181. It also adds documentation to `Weak::with_guaranteed_finalizer` and `Weak::clone_with_guaranteed_finalizer`.
**_Do not merge before #1181._**
=> Update and improve documentation about finalizers

src/context.rs, tests/test_api.rs
Closes https://github.com/denoland/rusty_v8/issues/1180
=> refactor: v8::Context::set_promise_hooks requires scope

src/binding.cc, src/context.rs, src/scope.rs, tests/test_api.rs
Adds bindings for:
- `v8::Context::GetContinuationPreservedEmbedderData`
- `v8::Context::SetContinuationPreservedEmbedderData`
These APIs are available on the `HandleScope`.
These are needed for new implementation of `AsyncLocalStorage`.
=> feat: Add bindings for continuation embedder data

src/binding.cc, src/property_descriptor.rs, tests/test_api.rs
Adds `PropertyDescriptor::new_from_value_writable` and `PropertyDescriptor::new_from_value` construct methods.
Used in Node-API https://github.com/nodejs/node/blob/main/src/js_native_api_v8.cc#L1228-L1231
=> Add PropertyDescriptor::new_from_value_writable and new_from_value

tests/test_api.rs
Appears this test could be run in parallel with other tests which could interfere
with hashing algorithm used in "v8::script_compiler::cached_data_version_tag" API.
Closes https://github.com/denoland/rusty_v8/issues/1183
=> test: fix flaky cached_data_version_tag test

src/binding.cc, src/context.rs, tests/test_api.rs
This PR enables the security token [api](https://v8.dev/docs/embed#security-model) to be able to share data between different context
=> feat: Expose the security token API from V8

tests/test_api.rs
Preparing to remove my added check for UTF-8 correctness in Deno FFI's `getCString` binding.
It seems that the `new_from_utf8` API is indeed resilient against invalid UTF-8 sequences. The lengths asserted in these tests correspond to the expectations that I get from doing `new TextDecoder().decode(Uint8Array.from([...])).length` in Chrome DevTools and in Deno CLI REPL.
Test sequences are copied over from Stack Overflow: https://stackoverflow.com/a/3886015
=> Add tests for invalid UTF-8 sequences in v8::String::new_from_utf8

.github/workflows/release.yml
`dtolnay/rust-toolchain@stable` is broken, see https://github.com/dtolnay/rust-toolchain/issues/77
=> Use dsherret/rust-toolchain-file@v1 for release CI

README.md, build.rs
macOS no longer ships with `python` symlinked, so let's add
an environment variable so that people can easily build rusty_v8.
=> build: add PYTHON envvar to specify your python binary

src/fast_api.rs, tests/test_api.rs
This commit removes the `as_str()` method and adds the `as_bytes` method to access the Latin-1 data. The utf8 assumption is wrong, the application should validate before converting to Rust string.
=> FastApiOneByteString is not always utf-8

src/script.rs, tests/test_api.rs
Reproduces https://github.com/denoland/rusty_v8/issues/1226 and https://github.com/denoland/deno/issues/19021
```
// Fails
$ V8_FROM_SOURCE=1 cargo test exception
// Passes
$ V8_FROM_SOURCE=1 cargo test --release exception
```
We bisected this and this problem first appeared with V8 v11.2 upgrade. After further
bisects we established that https://github.com/v8/v8/commit/1f349da554800d9278cd1472850ca90a1fd7dc1e#diff-de75fc3e7b84373d94e18b4531827e8b749f9bbe05b59707e894e4e0ce2a1535
is the first V8 commit that causes this failure. However after more investigation we can't
find any reason why that particular commit might cause this problem.
It is only reproducible in debug build, but not release build. Current working theory
is that it is a Rust compiler bug as changing the optimization level …
=> test: Add tests showing incorrect exception behavior in debug build

src/function.rs, tests/test_api.rs
Follow up to https://github.com/denoland/rusty_v8/commit/6ac0fabb56ea20a4ec778d014eedb7f8a3bc0ec7 which
exhibits the same bug in `v8::Function::call`.
This will allow to fix https://github.com/denoland/deno/issues/19021 (checked in local build).
=> Fix exception not caught in debug build for v8::Function::call

src/isolate_create_params.rs, tests/test_api.rs
Needed for `deno_core` so that if we want to use jemalloc we can do so
conditionally only if `deno_core` embedder hasn't set an allocator already.
=> feat: Add v8::CreateParams::has_set_array_buffer_allocator

src/binding.cc, src/object.rs, src/property_attribute.rs, tests/test_api.rs
Specifically Object::get_own_property_descriptor
and Object::get_property_attributes
=> Add more Object methods

src/binding.cc, src/fast_api.rs, src/template.rs, tests/test_api.rs
The new V8 supports fast calls returning 64-bit integers. With the default setting of `Int64Representation::kNumber` this just means that return values can be lossy 64-bit integers. Any data loss is, as they say, your problem.
With `Int64Representation::kBigInt` all 64-bit integers both on the parameter and return value side will be handled as BigInts: Calling `fast_call(32234646)` will never enter the fast call path with this representation but instead `fast_call(3234226n)` needs to be used. With this representation, any 64-bit integer return values are of course also returned as BigInts.
Performance measurements performed by a V8 intern gave numbers like this:
Microbenchmark | Operand range | As Number (us) | BigInt Only (us)
-- | -- | -- | --
Call-and-store | Smi (31-bit signed) | …
=> feat(fastcall): Int64Representation

src/binding.cc, src/function.rs, src/script.rs, tests/test_api.rs
I added the bindings in the title to use in an application! Let me know if I'm missing anything.
=> Add `Function::{ScriptId, GetScriptOrigin}, ScriptOrigin::Get{ScriptId, ResourceName, SourceMapUrl}` bindings

src/string.rs, tests/test_api.rs
Follow-on fix for #1256 -- Latin-1 strings may expand in their UTF-8 representation.
=> fix: Ensure that one-byte strings that are not ASCII go through write_utf8_uninit

src/scope.rs
this warning only occurs when using the library as a dependency.
```
warning: unused return value of `Box::<T>::from_raw` that must be used
--> /rusty_v8/src/scope.rs:1092:16
|
1092 |       unsafe { Box::from_raw(root) };
|                ^^^^^^^^^^^^^^^^^^^
|
= note: call `drop(Box::from_raw(ptr))` if you intend to drop the `Box`
= note: `#[warn(unused_must_use)]` on by default
```
=> silence warning for unused 'must use'

src/template.rs, tests/test_api.rs
Needed for https://github.com/denoland/deno/pull/19307 due to possible Rust compiler bug.
This commit adds methods for setting "raw" callback that need to be `.map_fn_to()` manually
by a user.
=> Add v8::NamedPropertyHandlerConfiguration::*_raw methods

src/fast_api.rs
`copy_nonoverlapping` is not valid to use here as:
Behavior is undefined if any of the following conditions are violated:
src must be [valid](https://doc.rust-lang.org/stable/std/ptr/index.html#safety) for reads of count * size_of::<T>() bytes.
dst must be [valid](https://doc.rust-lang.org/stable/std/ptr/index.html#safety) for writes of count * size_of::<T>() bytes.
Both src and dst must be properly aligned.
The region of memory beginning at src with a size of count * size_of::<T>() bytes must not overlap with the region of memory beginning at dst with the same size.
=> fix: Use unaligned read as copy_nonoverlapping requires alignment

src/binding.cc
Recent static assert additions did not either use size_t based assertions or would not function with them because of padding required. This PR tries to fix the issue.
=> fix: 32-bit build fails on non-size_t based size assertions

README.md
"In the limit…" should probably read "In the end…" or "In the future…", but the last sentence makes the first redundant, so this PR removes the confusing sentence.
=> Remove a redundant and confusing sentence from FAQ

.gn, src/binding.cc
The memory leak caused by the EPT table not being subject to garbage collection is apparently still there.
=> chore: turn pointer compression off again

src/binding.cc, src/lib.rs, src/platform.rs, tests/slots.rs, tests/test_api.rs, tests/test_api_entropy_source.rs, tests/test_api_flags.rs, tests/test_platform_atomics_pump_message_loop.rs
This fixes the issue.
It needs some comments explaining why one would need `new_unprotected_default_platform()` (see TODOs).
@mmastrac Can you help out with that?
=> fix: crash on x86_64 systems that support memory protection keys

src/symbol.rs, tests/test_api.rs
`for_global` was documented as `for_key` but implemented as `for_api`.
Closes #1323
=> fix(Symbol): deprecate `for_global` in favour of `for_key` and `for_api`

src/array_buffer_view.rs, src/binding.cc, tests/test_api.rs
Using this method, we can get the underlying buffers for TypedArrays without requiring a scope to be created.
=> feat: add scope-less data() access on ArrayBufferView

Cargo.lock, Cargo.toml, src/array_buffer.rs, src/binding.cc, src/shared_array_buffer.rs, tests/test_api.rs
Allow creation of `v8::ArrayBuffer` and `v8::SharedArrayBuffer` from things that `DerefMut` to `&mut [u8]`. We stash the underlying object in a `Box` and then keep its slice around in the form of a buffer until we destroy the buffer. There's no way to take the object out of the buffer for now.
This is useful for when we want to return a `BytesMut` to v8.
We also expose an `empty` method for both buffers so we can avoid the overhead when creating empty buffers of any type.
=> feat: new_backing_store_from_bytes and empty for ArrayBuffer and SharedArrayBuffer

src/array_buffer.rs, src/shared_array_buffer.rs, tests/test_api.rs
If a vector tried to shrink during the `into_boxed_slice` operation, the slice we took before would become invalid.
=> fix: arraybuffer init from vec was broken if vec reallocated to box

src/array_buffer_view.rs, tests/test_api.rs
Allows for scope-free access to ArrayBufferView's backing store
=> feat: add get_backing_store to ArrayBufferView

src/function.rs, tests/test_api.rs
Allows calling of a function without creation of a `HandleScope<'s>` (that is, from an `Isolate` -- `HandleScope<'s, ()>`.
This shows a small improvement in some deno_core experiments.
=> feat: add call_with_context to v8::Function

README.md
In this PR, I have fixed the broken link of releases in README.md file which previously used to redirect to a 404 page.
Fixes #1356
=> Fixed the broken link of releases in README

examples/cppgc-object.rs, examples/cppgc.rs, src/binding.cc, src/cppgc.rs, src/isolate.rs, src/lib.rs, tests/test_cppgc.rs
https://v8.dev/blog/high-performance-cpp-gc
Oilpan in Deno design doc: https://www.notion.so/denolandinc/Oilpan-cppgc-in-Deno-e194f4268e9f4135ba97610ff7d3a949?pvs=4
Oilpan can be used to implement GC'able resources in Deno
Closes https://github.com/denoland/rusty_v8/issues/933
=> Add `cppgc` bindings

src/binding.cc, src/value_serializer.rs, tests/test_api.rs
Add v8::ValueSerializerImpl::{has_custom_host_object,is_host_object} equivalents for v8::ValueSerializer::Delegate::{HasCustomHostObject,IsCustomHostObject}.
This enables serializing custom host objects without embedder fields.
* V8 commit: v8/v8@cf13b9b46572a9824d2d632abdd48c56161ace02
* V8 bug: https://bugs.chromium.org/p/v8/issues/detail?id=11927
* Deno bug: denoland/deno#12067
=> feat: Support custom host objects in ValueSerializer

examples/android/Cargo.toml
This example causes rust-analyzer to complain about the `ndk` crate.
=> chore: disable android example deps on non-android platforms

src/binding.cc, src/isolate.rs, tests/test_api.rs
Due to the automatic entry and exit behavior of Isolate upon creation and drop, it is crucial to ensure that v8::OwnedIsolate instances are dropped in the reverse order of their creation. Dropping them in the incorrect order can result in the corruption of the thread-local stack managed by v8, leading to memory corruption and potential segfaults. 
This introduces a check to verify the `this == Isolate::GetCurrent()` requirement before invoking the exit function. If the requirement is not met, a clean panic is triggered to provide explicit error handling instead of allowing silent memory corruption.
The following program demonstrates how a segfault can be currently triggered using only the safe Rust API:
```rust
fn main() {
let platform = v8::new_default_platform(0, false).make_shared(); …
```
=> Explicit panic instead of silent memory corruption

examples/cppgc-object.rs, src/binding.cc, src/isolate.rs, src/isolate_create_params.rs, src/scope.rs, src/script.rs, src/script_compiler.rs, src/snapshot.rs, src/value_serializer.rs, tests/test_api.rs, tests/test_cppgc.rs
Changes:
#1373 but without denobot force pushing over our changes :)
=> Upgrade to V8 12.1.285.6

examples/cppgc-object.rs, src/isolate.rs, tests/test_cppgc.rs
Changes `v8::Isolate::get_cpp_heap` to return a `Option<&Heap>`.
=> `isolate->GetCppHeap()` can return nullptr if no heap is attached

src/property_handler_flags.rs, tests/test_api.rs
Ref https://chromium-review.googlesource.com/c/v8/v8/+/5006387
=> Remove AllCanRead flag from PropertyHandlerFlags

src/bigint.rs
The original documentation was unclear about the value of the bool. I interpreted it as being `true` if the value was truncated.
=> Fix misleading BigInt rustdoc

src/scope.rs, tests/test_api.rs
`v8::Data` is `TryFrom<v8::Data`, but the error is `Infallible` so these methods didn't work for the generic type `v8::Data`.
We can add a private trait that will allow us to work with `v8::Data` in these APIs.
=> feat: allow v8::Data as a generic for get_*_from_snapshot_once

src/isolate.rs
Tis was a drive-by fix, callers spelled it correctly and the C++ side was also spelled correctly.
=> Fixed a typo in the parameter `capture` in `v8__Isolate__SetCaptureStackTraceForUncaughtExceptions`

.gn, README.md, src/binding.cc, src/isolate.rs, src/module.rs, tests/test_api.rs, tools/auto_update_v8.ts
This commit reverts:
- f30c18c77084acc46f5f0fad6969009be9972423
- 07436bdb4c396874ccad39e5f346c4b6f2ab1a8a
We have difficulties updating `deno_core` and `deno` to use V8 12.3
because of potential bug in named property handler for `globalThis`
(see https://github.com/denoland/rusty_v8/pull/1412).
We're reverting to tracking `12.2` branch for the time being to unblock
other work needed.
=> chore: revert V8 upgrade from 12.3 to 12.2.

src/binding.cc, src/isolate.rs, src/lib.rs, tests/test_api.rs
=> Add `Isolate::add_message_listener_with_error_level`

src/template.rs
Matches implementation of NamedPropertyHandlerConfiguration.
This is necessary to polyfill `node:vm` module in Deno.
=> feat: Add IndexedPropertyHandlerConfiguration::*_raw methods

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, build.rs
This helps download artifacts on flaky or slow networks. We save about 75% of the download required for most of these archives.
We'll need to do a release after we land this one to avoid a case where main can't be built.
=> feat: .gz compress release artifacts

src/object.rs, tests/test_api.rs
I made a mistake in https://github.com/denoland/rusty_v8/pull/1428.
Added some tests.
=> fix: mispelling in C binding

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, build.rs, src/V8.rs, src/binding.cc, src/isolate.rs, src/scope.rs, tests/test_api.rs, tests/test_ui.rs
Runs ASAN on every build as part of the Mac runs. I wasn't able to get this working for Linux :/ 
- Requires fixing +nightly warnings.
- One ASAN issue found: fast functions w/an overload were accessing the stack after a scope was destroyed.
=> chore: Allow Rust ASAN flags to propagate into v8 build

src/binding.cc, src/fast_api.rs
This deallocates the C++ allocation, preventing a memory leak
=> Impl Drop for CTypeInfo

src/binding.cc, src/fast_api.rs
This deallocates the C++ allocation, preventing a memory leak
=> Add Drop impl for CFunctionInfo

.cargo/config.toml, .github/workflows/ci.yml, Cross.toml, Dockerfile, README.md, build.rs, tests/test_api.rs
Add cross build for x64 android and arm64 android.
Tests skipped pass on a real device, the qemu trigger overflow due to some issues on the memory mapping.
Confirmed by [littledivy](https://github.com/littledivy) and me.
Passed CI: https://github.com/Taknok/rusty_v8/actions/runs/8764258824
Related issues:
#970 
#1303
=> For #970 & #1303 : Enable build for aarch64-linux-android & x86_64-linux-android

src/fast_api.rs, src/inspector.rs
Deleting invalidates the target of `&mut`. While the reference is no longer _used_ after this call, it must continue to be valid, making all calls to DELETE with refs unsound.
=> fix: don't pass refs to DELETE

.github/workflows/ci.yml, build.rs, rust-toolchain.toml
1. [Fixed incorrect use of cfg! macro](https://github.com/denoland/rusty_v8/commit/328f31f5a197476b3475bbcd5383cdc08364c863) use the `CARGO_CFG_TARGET_<OS/ARCH>` macro instead of the original `cfg! (target_<os/arch>)` This is because The build script is compiled for the host architecture as a separate build phase, as that's where it runs. Since the cfg macro runs at compile time it'll always report the host configuration there.When cargo runs the build script it passes the configuration through [environment variables](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts), one of which is `CARGO_CFG_TARGET_ARCH`. Some dicussions can be found [here](https://users.rust-lang.org/t/failed-to-detect-target-arch-in-build-rs-file/1 …
=> chore: Fixed incorrect use of cfg! macro and update build.rs to support arm target

.github/workflows/ci.yml, .gn, src/binding.cc, tests/test_api.rs
Re-land pointer compression now that @wingo's external pointer table GC changeset has landed.
Reverts https://github.com/denoland/rusty_v8/pull/1302 / https://github.com/denoland/rusty_v8/pull/1214
=> fix: Re-enable pointer compression

src/binding.cc, src/external_references.rs, src/function.rs, src/template.rs, tests/test_api.rs
This commit updates APIs related to named and indexed property
handlers to not use deprecated V8 APIs. Main change is the change
of return value in callbacks that now requires to return `v8::Intercepted` enum.
Towards https://github.com/denoland/rusty_v8/issues/1478
=> chore: Update use of deprecated APIs

src/binding.cc
This pull request fixes the type size checking on 32-bit platforms in `src/binding.cpp`.
On 32-bit platforms like armv7 or ppc32, the size of `v8::ScriptCompiler::CompilationDetails` and `v8::ScriptCompiler::Source` will be different than currently expected. This is due to how those 32-bit platforms lay out the 64-bit elements in a structure.
You can see a reduced example on Compiler Explorer: https://godbolt.org/z/TG1bPGG8n.
=> fix: fix size checking on 32-bit platforms

.github/workflows/ci.yml
After adding the Android support the CI fails on tags because `cargo publish` was being run
on linux GNU and linux Android.
=> build: fix publishing step

src/context.rs, tests/test_api.rs
Attempts to `clear_all_slots` would crash when annex slot is not intialized but is also non-null garbage value. This patch makes sure we initialize a valid annex slot.
=> Fix uninitialized context annex slot

src/binding.cc, src/template.rs, tests/test_api.rs
Implements [v8::Template::SetIntrinsicDataProperty](https://v8.github.io/api/head/classv8_1_1Template.html#aef172ef714818a210d815de389a5ab77) and the [Intrinsic](https://v8.github.io/api/head/namespacev8.html#a67f8ea6a2abeace49b9658da6a3267ab) enum. 
Fairly new to v8 and rust, so somebody please sanity check this 😅
=> Add `v8::Template::set_intrinsic_data_property`

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, build.rs, src/binding.cc, src/binding.hpp, src/binding.rs, src/lib.rs, src/script.rs, tools/get_bindgen_args.py
Adds bindgen, which is a little bit complex due to build being inside `gn`. I moved a `sizeof` definition over just as a basic test but we should be able to migrate the entire struct definition and others in the future.
=> feat: rust bindgen and publish flow

src/binding.cc, src/unbound_module_script.rs, src/unbound_script.rs, tests/test_api.rs
This commit adds bindings for:
- `v8::UnboundScript::get_source_mapping_url`
- `v8::UnboundScript::get_source_url`
- `v8::UnboundModuleScript::get_source_mapping_url`
- `v8::UnboundModuleScript::get_source_url`
=> feat: Add Source Maps APIs

build.rs
Fixes failures like this:
```
--- stderr
thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\v8-0.95.0\build.rs:851:46:
symlink_dir failed: Os { code: 183, kind: AlreadyExists, message: "Cannot create a file when that file already exists." }
stack backtrace:
0:     0x7ff65a7eb788 - std::backtrace_rs::backtrace::dbghelp64::trace
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
1:     0x7ff65a7eb788 - std::backtrace_rs::backtrace::trace_unsynchronized
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
2:     0x7ff65a7eb788 - std::sys_common::backtrace::_print_fmt
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\s …
```
=> build: remove symlink on Windows before creating it

.gn
can still be disabled at runtime with `--no-maglev`
also remove unused `deno_enable_extras` param
=> feat: enable maglev

examples/cppgc.rs, src/binding.cc, src/cppgc.rs, src/object.rs, tests/test_cppgc.rs
I avoided this before because there's no way to make this type as safe as it should be, and Member<T> was convenient enough, but Member<T> is slower to construct and read/write from due to its internals, and it is also difficult to work with due to being nullable. This also enables some very useful API improvements in deno_core to unlock cppgc `Resource` types.
=> feat: cppgc::Ptr

examples/process.rs, examples/shell.rs, src/handle.rs, tests/test_api.rs
Adds `cast` and `try_cast` methods to `v8::Local`, to make casting more ergonomic. There was already an existing `cast` function on `Local`, which did an unchecked cast. This PR renames the old `cast` to `cast_unchecked` for clarity (and so we can repurpose `cast`).
Currently, to go from `v8::Local<A>` to `v8::Local<B>`, in order to guide type inference you often end up writing
```rust
v8::Local::<v8::Function>::try_from(v8_value);
// try_into is no better because you can't easily give a type annotation
let func: v8::Local<v8::Function> = v8_value.try_into().unwrap();
```
We have > 100 instances of this in `test_api.rs` alone, and `deno` is similar.
With this PR, you can instead use the turbofish the give the type annotation
```rust
if let Ok(func) = v8_value.try_cast::<v8::Function>() { …
```
=> chore: Add a couple convenience casting functions to `v8::Local`

src/string.rs, tests/test_api.rs
A subtle unsoundness / undefined behaviour made its way into the fairly recently added `ExternalOneByteStringResource` object: The `as_str` API is not sound as the data inside may be be Latin-1, not ASCII.
As the API was not used anywhere in deno or deno_core, I opted to simply remove it and replace it with an `as_bytes` API. I also modified the test to showcase the Latin-1 string case and added copious notes and explanations around the code to make sure this doesn't accidentally happen again. The likely reason why the API originally slipped in is because the `OneByteConst` has this API where it _is_ safe because the `OneByteConst` creation checks the data for ASCII-ness.
I also tried to add an API to extract an `Option<&'static OneByteConst>` from an `&ExternalOneByteStringResource` but …
=> fix: ExternalOneByteStringResource is not guaranteed to be valid UTF-8

.gn
https://issues.chromium.org/issues/42210615
> Add a new build flag v8_enable_private_mapping_fork_optimization which
marks all pages allocated by OS::Allocate as MADV_DONTFORK. This
improves the performance of Node.js's fork/execve combination by 10x on
a 600 MB heap.
https://chromium-review.googlesource.com/c/v8/v8/+/4602858
https://lobste.rs/s/tr8ozm/why_is_spawning_new_process_node_so_slow
=> set v8_enable_private_mapping_fork_optimization = true

.gn, README.md, src/binding.cc, src/external_references.rs, src/fast_api.rs, src/function.rs, src/handle.rs, src/scope.rs, src/template.rs, tests/test_api.rs, tests/test_cppgc.rs
~~Thankfully not too many changes needed :)~~ spoke too soon! specializes `ReturnValue<T>` on Value-likes and `()` to make setters safe.
=> feat: V8 12.8

.gn
`-rusty` seemed like the best option since this library is used by more than just deno.
=> add embedder suffix to v8 version

examples/shell.rs, src/binding.cc, src/isolate.rs, src/scope.rs, src/script.rs, tests/test_api.rs
I meant to get this into the 0.100.0 release but forgot. This allows setting `host_defined_options` which will be useful in deno for fixing global modes and and improving `node:vm` compat.
=> feat: upgrade ScriptOrigin

.github/workflows/ci.yml, build.rs, src/binding.cc, src/binding.hpp, src/cppgc.rs, src/handle.rs, src/script.rs, src/string.rs, src/support.h, src/typed_array.rs, tests/test_api.rs
Gets rid of some superfluous functions and also deletes the unneeded `RUST_` prefix. also fixed a missing destructor.
=> chore: binding cleanup

.github/workflows/ci.yml
we don't use android, it takes forever, and `cross clippy` is causing sporadic ci failures on rust 1.80
=> chore: disable android in ci

benches/function.rs, examples/cppgc-object.rs, examples/hello_world.rs, examples/process.rs, examples/shell.rs, src/binding.cc, src/context.rs, src/isolate.rs, src/lib.rs, src/object.rs, src/scope.rs, src/script_compiler.rs, tests/compile_fail/try_catch_exception_lifetime.rs, tests/compile_fail/try_catch_message_lifetime.rs, tests/slots.rs, tests/test_api.rs, tests/test_api_entropy_source.rs, tests/test_api_flags.rs, tests/test_cppgc.rs, tests/test_platform_atomics_pump_message_loop.rs, tests/test_single_threaded_default_platform.rs
- Context::new takes options
- add Isolate::SetAllowWasmCodeGenerationCallback
- Annex slots can be accessed without passing `scope` (used in deno inside code generation callback)
- add Object::HasRealNamedProperty
Fixes: #1438
=> feat: changes for vm

.gn, tests/test_api.rs
Fixes https://github.com/denoland/rusty_v8/issues/1475
> This is safe to enable only when all C++ code is built with the
flag set to the same value.
This is enabled by default for Android builds but our OneByteConst code assume pointer vtables.
=> Disable relative vtable on Android

.gn, src/binding.cc
This causes issues with heap cages, limiting the process to 4G of heap, and also may prevent use of upcoming js features like shared structs.
=> disable pointer compression

src/binding.cc, src/value_deserializer.rs, src/value_serializer.rs, tests/test_api.rs
Currently, if you were to call (for instance) `write_value` as part of a custom `write_host_object` implementation, you would be forced to create aliased exclusive references to the serializer (which is instant UB).
The underlying v8 de/serializers are re-entrant, so for the most part we simply need to pass around shared references instead of exclusive references.
Also adds some bindings to some missing functions, and makes `ValueSerializer` (and deserializer) garbage collectable.
=> Allow `ValueSerializerImpl` and `ValueDeserializerImpl` impls to be re-entrant

src/value_serializer.rs, tests/test_api.rs
The internal buffer pointer gets set to null upon release, and then returned by v8 to us.
=> fix: Check for null pointer returned by `ValueSerializer::Release`

Cargo.lock, Cargo.toml
To pick up https://github.com/denoland/rusty_v8/commit/eb29f6bd8cf9c259303613e19377fb44f626bf4b plus some v8 fixes.
=> Update to v0.105.1

.gn, src/binding.cc, src/cppgc.rs, src/isolate.rs, tests/test_cppgc.rs
blink is still only manually attaching cppgc heaps, and the other code paths are untested, so continue exposing this to avoid bugs (for example: https://github.com/denoland/deno_core/issues/894)
=> re-add deprecated cppgc api

build.rs, src/binding.cc, src/binding.hpp, src/cppgc.rs, src/object.rs, src/support.h, tests/test_cppgc.rs
implements NameProvider, but I didn't want RustObj to grow beyond 2 pointers, so replace it with a dyn pointer and use that to dispatch.
=> feat: cppgc NameProvider

.github/workflows/ci.yml
Fixes this spam on CI runs:
> The following actions use a deprecated Node.js version and will be forced to run on node20: actions/setup-python@v4, actions/cache@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> upgrade deprecated workflow actions

Cargo.lock, Cargo.toml
To pick up this fix: https://github.com/rust-lang/rust-bindgen/commit/600f63895f73c80d6bf7ff3c71b86a068d1663d2
=> Update bindgen to fix builds with LLVM 19.1

.github/workflows/ci.yml, Cargo.lock, rust-toolchain.toml, tests/test_api.rs
go back to 22.04 to fix glibc version. updates clang for newer features used in v8. also requires a rust toolchain upgrade to build correctly for mysterious and unknown reasons.
Fixes: https://github.com/denoland/rusty_v8/issues/1655
=> fix: glibc version

src/isolate.rs
This pull request includes a documentation update to the `HostInitializeImportMetaObjectCallback` type in the `src/isolate.rs` file. The update clarifies the meaning of the `host_defined_options` and `resource_name` parameters.
fixes #1349 
Documentation improvements:
Updated comments to explain that `host_defined_options` are metadata provided by the host environment for customizing module imports, and `resource_name` is the identifier or path for the module or script making the import request.
=> Improves documentation for HostImportModuleDynamicallyCallback

examples/cppgc-object.rs, examples/cppgc.rs, src/binding.cc, src/cppgc.rs, src/support.h, tests/test_cppgc.rs
cppgc supports exactly two alignments: 8 byte and 16 byte. We can support this by dispatching to a different base C++ class.
Fixes: https://github.com/denoland/rusty_v8/issues/1676
=> fix: let cppgc align to 16 bytes

src/array_buffer.rs, src/shared_array_buffer.rs, tests/test_api.rs
for implementing more signature types in op2
=> implement Rawable for all TypedArray types

Cargo.lock, Cargo.toml, src/cppgc.rs
We need to add this back until we do a major release.
=> fix: add back incorrectly spelled initalize_process

src/binding.cc, src/string.rs, tests/test_api.rs
Brings back String APIs removed in https://github.com/denoland/rusty_v8/pull/1692
and renamed the new APIs to have `_v2` suffix.
=> feat: Bring back deprecated v8::String API

build.rs, examples/cppgc-object.rs, src/array_buffer.rs, src/context.rs, src/handle.rs, src/isolate.rs, src/module.rs, src/script.rs, src/script_compiler.rs, src/support.rs, src/wasm.rs, tests/test_cppgc.rs
auto-fixed trailing semicolons by running
```
clippy --fix --all-features --all-targets --workspace -- -W clippy::map_unwrap_or
```
See [`map_unwrap_or`](https://rust-lang.github.io/rust-clippy/master/index.html#map_unwrap_or) clippy lint.
=> chore: fix map_unwrap_or clippy lint

build.rs, src/V8.rs, src/bigint.rs, src/context.rs, src/cppgc.rs, src/handle.rs, src/inspector.rs, src/isolate.rs, src/isolate_create_params.rs, src/object.rs, src/platform.rs, src/primitive_array.rs, src/scope.rs, src/shared_array_buffer.rs, src/template.rs, src/value.rs, src/value_deserializer.rs, src/value_serializer.rs, src/wasm.rs, tests/test_api.rs
auto-fixed trailing semicolons by running
```
clippy --fix --all-features --all-targets --workspace -- -W clippy::semicolon_if_nothing_returned
```
See [`semicolon_if_nothing_returned`](https://rust-lang.github.io/rust-clippy/master/index.html#semicolon_if_nothing_returned) clippy lint.
=> chore: fix semicolons

benches/function.rs, build.rs, examples/android/lib.rs, examples/cppgc-object.rs, examples/cppgc.rs, examples/process.rs, examples/shell.rs, src/data.rs, src/inspector.rs, src/support.rs, src/wasm.rs, tests/test_api.rs, tests/test_concurrent_isolate_creation_and_disposal.rs, tests/test_cppgc.rs
Apply [`uninlined_format_args`](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args) clippy lint -- makes code a bit more readable.
=> chore: cleanup format args

src/array_buffer_view.rs, src/binding.cc, src/support.h, src/template.rs
This needs to provide some form of mutable API. Returns a raw pointer due to rust aliasing rules, and marked unsafe since you have to manually ensure the view is rooted the entire time you are using that raw pointer.
=> feat: add get_contents_raw_parts

src/binding.cc, src/string.rs, tests/test_api.rs
WriteUtf8V2 didn't have this parameter originally, but now it does!
=> Add WriteUtf8V2 missing param fix

src/array_buffer.rs, src/binding.cc, src/isolate.rs, src/shared_array_buffer.rs, src/support.h, src/value.rs, tests/test_api.rs
Remove use of internal V8 APIs. some could be removed as-is, others will require changes coming in 13.5. Ultimately this includes some breaking changes as well, so waiting for 13.5 is ok.
=> Remove use of internal V8 apis

src/isolate.rs
this value is very difficult to use for metrics if the lifetime is not static.
=> fix: space_name is static

.github/workflows/ci.yml
1. Bumps `sccache` to v0.8.2, it is originally from here [PR-1663](https://github.com/denoland/rusty_v8/pull/1663/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL152).
2. Bumps `setup-python` to v5.
=> ci: bump 'sccache' to v0.8.2

src/isolate.rs
This adds `#[derive(Debug, Clone, Copy, PartialEq, Eq)]` and `#[repr(C)]` to the `MemoryPressureLevel` enum to ensure consistent memory layout and enable common trait implementations.
=> fix: add auto derivation and repr(C) to `MemoryPressureLevel`

src/binding.cc, src/isolate.rs, src/platform.rs
Without this, the isolate's ForegroundTaskRunner (stored in the platform) leaks.
=> Call Platform::NotifyIsolateShutdown before disposing isolate

src/binding.cc, src/external_references.rs, src/function.rs, src/handle.rs, src/isolate.rs, src/isolate_create_params.rs, src/lib.rs, src/object.rs, src/scope.rs, src/snapshot.rs, src/support.rs, src/template.rs, tests/test_api.rs, tests/test_external_deserialize.rs
Simpify apis for isolate-owned data (startup snapshot and external references). Notably this finally makes it possible to use external references without `transmute`. function callbacks are also refactored to get rid of the incorrect lifetime they contained, which leaked into ExternalReference.
=> clean up Allocated apis

src/binding.cc, src/context.rs, tests/test_api.rs
Similar to `set_aligned_pointer_in_embedder_data` but lets you set `Value`s rather than pointers.
=> Add Context::{get,set}_embedder_data

src/script_compiler.rs
This simply converts the enum to bitflags while retaining backwards compatibility.
=> feat: convert CompileOptions to bitflags

src/array_buffer.rs, src/data.rs, src/object.rs, src/scope.rs, src/string.rs
While benchmarking `facet-v8`, some surprising `rusty_v8` functions showed up that I would have expected to be either compiled out or be direct calls to the C ABI shim - even with LTO enabled.
I went and added `#[inline]` to a bunch of functions that looked like they should have it - particularly `v8::HandleScope::deref/_mut()`, which seemed to affect inlining heuristics nicely, giving a small perf boost.
=> Inline some obvious candidates (ops, small functions)

.gitignore, .gitmodules, .gn, Cargo.lock, Cargo.toml, build.rs, src/lib.rs, tools/download_file.py, tools/ninja_gn_binaries.py, tools/rust_toolchain.py
Fixes #1839
I needed to patch temporal_capi to depend on temporal_rs 0.0.11 exactly: https://crates.io/crates/ry_temporal_capi/0.0.11-ry.1
=> feat: add back `Temporal` support
